Attribute VB_Name = "Litecad"

Public Const LC_FALSE = 0
Public Const LC_TRUE = 1
Public Const LC_LBUTTON = 1
Public Const LC_RBUTTON = 2
Public Const LC_MBUTTON = 4
Public Const LC_SHIFT = 1
Public Const LC_CTRL = 2
Public Const LC_ALT = 4
Public Const LC_WS_HSCROLL = 1
Public Const LC_WS_VSCROLL = 2
Public Const LC_WS_BORDER = 4
Public Const LC_WS_CLIENTEDGE = 8
Public Const LC_WS_SUNKEN = 8
Public Const LC_WS_STATICEDGE = 16
Public Const LC_WS_VIEWTABS = 256
Public Const LC_WS_DEFAULT = 3
Public Const LC_INSUNIT_UNDEFINED = 0
Public Const LC_INSUNIT_INCHES = 1
Public Const LC_INSUNIT_FEET = 2
Public Const LC_INSUNIT_MILES = 3
Public Const LC_INSUNIT_MILLIMETERS = 4
Public Const LC_INSUNIT_CENTIMETERS = 5
Public Const LC_INSUNIT_METERS = 6
Public Const LC_INSUNIT_KILOMETERS = 7
Public Const LC_INSUNIT_MICROINCHES = 8
Public Const LC_INSUNIT_MILS = 9
Public Const LC_INSUNIT_YARDS = 10
Public Const LC_INSUNIT_ANGSTROMS = 11
Public Const LC_INSUNIT_NANOMETERS = 12
Public Const LC_INSUNIT_MICRONS = 13
Public Const LC_INSUNIT_DECIMETERS = 14
Public Const LC_INSUNIT_DEKAMETERS = 15
Public Const LC_INSUNIT_HECTOMETERS = 16
Public Const LC_INSUNIT_GIGAMETERS = 17
Public Const LC_INSUNIT_ASTRONOMICAL = 18
Public Const LC_INSUNIT_LIGHTYEARS = 19
Public Const LC_INSUNIT_PARSECS = 20
Public Const LC_LUNIT_SCIEN = 1
Public Const LC_LUNIT_DECIM = 2
Public Const LC_LUNIT_ENGIN = 3
Public Const LC_LUNIT_ARCHI = 4
Public Const LC_LUNIT_FRACT = 5
Public Const LC_AUNIT_DEGREE = 0
Public Const LC_AUNIT_DMS = 1
Public Const LC_AUNIT_GRAD = 2
Public Const LC_AUNIT_RADIAN = 3
Public Const LC_AUNIT_SURVEY = 4
Public Const LC_ANGLE_DEGREE = 0
Public Const LC_ANGLE_DMS = 1
Public Const LC_ANGLE_GRAD = 2
Public Const LC_ANGLE_RADIAN = 3
Public Const LC_ANGLE_SURVEY = 4
Public Const LC_PI = 3.14159265358979323846
Public Const LC_PI2 = 1.57079632679489661923
Public Const LC_PI4 = 0.785398163397448309615
Public Const LC_2PI = 6.28318530717958647692
Public Const LC_DEG45 = 0.785398163397448309615
Public Const LC_DEG90 = 1.57079632679489661923
Public Const LC_DEG180 = 3.14159265358979323846
Public Const LC_DEG270 = 4.71238898038468985769
Public Const LC_DEG360 = 6.28318530717958647692
Public Const LC_RAD_TO_DEG = 57.2957795130823208
Public Const LC_DEG_TO_RAD = 0.0174532925199433
Public Const LC_VIEW_TOP = 0
Public Const LC_VIEW_PLAN = 0
Public Const LC_VIEW_BOTTOM = 1
Public Const LC_VIEW_LEFT = 2
Public Const LC_VIEW_RIGHT = 3
Public Const LC_VIEW_FRONT = 4
Public Const LC_VIEW_BACK = 5
Public Const LC_VIEW_SW = 6
Public Const LC_VIEW_SE = 7
Public Const LC_VIEW_NE = 8
Public Const LC_VIEW_NW = 9
Public Const LC_VIEW_ISOMETRIC = 10
Public Const LC_VIEW_PERSPECTIVE = 11
Public Const LC_PLANE_XY = 0
Public Const LC_PLANE_XZ = 1
Public Const LC_PLANE_YZ = 2
Public Const LC_PAPER_CUSTOM = 0
Public Const LC_PAPER_A0 = 1
Public Const LC_PAPER_A1 = 2
Public Const LC_PAPER_A2 = 3
Public Const LC_PAPER_A3 = 4
Public Const LC_PAPER_A4 = 5
Public Const LC_PAPER_A5 = 6
Public Const LC_PAPER_A6 = 7
Public Const LC_PAPER_B0 = 11
Public Const LC_PAPER_B1 = 12
Public Const LC_PAPER_B2 = 13
Public Const LC_PAPER_B3 = 14
Public Const LC_PAPER_B4 = 15
Public Const LC_PAPER_B5 = 16
Public Const LC_PAPER_B6 = 17
Public Const LC_PAPER_C0 = 21
Public Const LC_PAPER_C1 = 22
Public Const LC_PAPER_C2 = 23
Public Const LC_PAPER_C3 = 24
Public Const LC_PAPER_C4 = 25
Public Const LC_PAPER_C5 = 26
Public Const LC_PAPER_C6 = 27
Public Const LC_PAPER_ANSI_A = 31
Public Const LC_PAPER_ANSI_B = 32
Public Const LC_PAPER_ANSI_C = 33
Public Const LC_PAPER_ANSI_D = 34
Public Const LC_PAPER_ANSI_E = 35
Public Const LC_PAPER_LETTER = 36
Public Const LC_PAPER_LEGAL = 37
Public Const LC_PAPER_EXECUTIVE = 38
Public Const LC_PAPER_LEDGER = 39
Public Const LC_PAPER_PORTRAIT = 0
Public Const LC_PAPER_BOOK = 0
Public Const LC_PAPER_LANDSCAPE = 1
Public Const LC_PAPER_ALBUM = 1
Public Const LC_BLOCK_OVERWRITENO = 0
Public Const LC_BLOCK_OVERWRITEYES = 1
Public Const LC_BLOCK_OVERWRITEDLG = 2
Public Const LC_OBJ_LAYER = 1
Public Const LC_OBJ_LINETYPE = 2
Public Const LC_OBJ_TEXTSTYLE = 3
Public Const LC_OBJ_DIMSTYLE = 4
Public Const LC_OBJ_BLOCK = 5
Public Const LC_OBJ_IMAGE = 6
Public Const LC_OBJ_VIEW = 7
Public Const LC_OBJ_MLSTYLE = 8
Public Const LC_ENT_LINE = 101
Public Const LC_ENT_POLYLINE = 102
Public Const LC_ENT_CIRCLE = 103
Public Const LC_ENT_ARC = 104
Public Const LC_ENT_BLOCKREF = 105
Public Const LC_ENT_POINT = 107
Public Const LC_ENT_XLINE = 108
Public Const LC_ENT_ELLIPSE = 109
Public Const LC_ENT_TEXT = 110
Public Const LC_ENT_TEXTWIN = 111
Public Const LC_ENT_IMAGEREF = 115
Public Const LC_ENT_VIEWPORT = 116
Public Const LC_ENT_RECT = 118
Public Const LC_ENT_ATTRIB = 120
Public Const LC_ENT_ECW = 121
Public Const LC_ENT_MTEXT = 122
Public Const LC_ENT_ARCTEXT = 123
Public Const LC_ENT_HATCH = 124
Public Const LC_ENT_BEZIER = 125
Public Const LC_ENT_MLINE = 127
Public Const LC_ENT_DIMROT = 131
Public Const LC_ENT_DIMALI = 132
Public Const LC_ENT_DIMORD = 133
Public Const LC_ENT_DIMRAD = 134
Public Const LC_ENT_DIMDIA = 135
Public Const LC_ENT_DIMANG = 136
Public Const LC_ENT_LEADER = 137
Public Const LC_ENT_CUSTOM = 1000
Public Const LC_ENT_ALL = 32767
Public Const LC_LWEIGHT_DEFAULT = -3
Public Const LC_LWEIGHT_BYBLOCK = -2
Public Const LC_LWEIGHT_BYLAYER = -1
Public Const LC_LWEIGHT_000 = 0
Public Const LC_LWEIGHT_005 = 5
Public Const LC_LWEIGHT_009 = 9
Public Const LC_LWEIGHT_013 = 13
Public Const LC_LWEIGHT_015 = 15
Public Const LC_LWEIGHT_018 = 18
Public Const LC_LWEIGHT_020 = 20
Public Const LC_LWEIGHT_025 = 25
Public Const LC_LWEIGHT_030 = 30
Public Const LC_LWEIGHT_035 = 35
Public Const LC_LWEIGHT_040 = 40
Public Const LC_LWEIGHT_050 = 50
Public Const LC_LWEIGHT_053 = 53
Public Const LC_LWEIGHT_060 = 60
Public Const LC_LWEIGHT_070 = 70
Public Const LC_LWEIGHT_080 = 80
Public Const LC_LWEIGHT_090 = 90
Public Const LC_LWEIGHT_100 = 100
Public Const LC_LWEIGHT_106 = 106
Public Const LC_LWEIGHT_120 = 120
Public Const LC_LWEIGHT_140 = 140
Public Const LC_LWEIGHT_158 = 158
Public Const LC_LWEIGHT_200 = 200
Public Const LC_LWEIGHT_211 = 211
Public Const LC_KBD_QWERTY = 0
Public Const LC_KBD_AZERTY = 1
Public Const LC_CMD_FILESAVE = 4
Public Const LC_CMD_FILESAVEAS = 5
Public Const LC_CMD_PRINT = 7
Public Const LC_CMD_RASTERIZE = 8
Public Const LC_CMD_POINT = 201
Public Const LC_CMD_LINE = 202
Public Const LC_CMD_XLINE = 203
Public Const LC_CMD_RAY = 204
Public Const LC_CMD_PLINE = 205
Public Const LC_CMD_POLYLINE = 205
Public Const LC_CMD_RECT = 206
Public Const LC_CMD_CIRCLE = 207
Public Const LC_CMD_ARC = 208
Public Const LC_CMD_ELLIPSE = 209
Public Const LC_CMD_TEXT = 210
Public Const LC_CMD_MTEXT = 211
Public Const LC_CMD_ATEXT = 212
Public Const LC_CMD_INSERT = 213
Public Const LC_CMD_VPORT = 214
Public Const LC_CMD_BASEPOINT = 215
Public Const LC_CMD_ATTDEF = 216
Public Const LC_CMD_HATCH = 217
Public Const LC_CMD_BOUNDARY = 218
Public Const LC_CMD_WTEXT = 219
Public Const LC_CMD_DIMROT = 231
Public Const LC_CMD_DIMALI = 232
Public Const LC_CMD_DIMORD = 233
Public Const LC_CMD_DIMRAD = 234
Public Const LC_CMD_DIMDIA = 235
Public Const LC_CMD_DIMANG = 236
Public Const LC_CMD_LEADER = 237
Public Const LC_CMD_CENTER = 238
Public Const LC_CMD_ECW = 239
Public Const LC_CMD_MLINE = 240
Public Const LC_CMD_CBCUT = 301
Public Const LC_CMD_CBCOPY = 302
Public Const LC_CMD_CBPASTE = 303
Public Const LC_CMD_UNDO = 304
Public Const LC_CMD_REDO = 305
Public Const LC_CMD_COPY = 306
Public Const LC_CMD_ERASE = 307
Public Const LC_CMD_MOVE = 308
Public Const LC_CMD_ROTATE = 309
Public Const LC_CMD_SCALE = 310
Public Const LC_CMD_MIRROR = 311
Public Const LC_CMD_EXPLODE = 312
Public Const LC_CMD_JOIN = 314
Public Const LC_CMD_DEP = 315
Public Const LC_CMD_ORDER = 316
Public Const LC_CMD_CLOSEBLOCK = 317
Public Const LC_CMD_TRIM = 318
Public Const LC_CMD_EXTEND = 319
Public Const LC_CMD_OFFSET = 320
Public Const LC_CMD_OFFSET_POINT = 0
Public Const LC_CMD_OFFSET_DIST = 1
Public Const LC_CMD_BREAK = 321
Public Const LC_CMD_VIEWSTART = 401
Public Const LC_CMD_ZOOM_IN = 401
Public Const LC_CMD_ZOOM_OUT = 402
Public Const LC_CMD_ZOOM_EXT = 403
Public Const LC_CMD_ZOOM_LIM = 404
Public Const LC_CMD_ZOOM_PREV = 405
Public Const LC_CMD_ZOOM_SEL = 406
Public Const LC_CMD_PAN_LEFT = 407
Public Const LC_CMD_PAN_RIGHT = 408
Public Const LC_CMD_PAN_UP = 409
Public Const LC_CMD_PAN_DOWN = 410
Public Const LC_CMD_VIEWEND = 410
Public Const LC_CMD_PAN_RT = 419
Public Const LC_CMD_ZOOM_RT = 420
Public Const LC_CMD_ZOOM_WIN = 421
Public Const LC_CMD_PAGENEXT = 423
Public Const LC_CMD_PAGEPREV = 424
Public Const LC_CMD_PAGEMODEL = 425
Public Const LC_CMD_PAGEVPORT = 426
Public Const LC_CMD_VP_ACT = 427
Public Const LC_CMD_VP_DEACT = 428
Public Const LC_CMD_VIEW_TOP = 430
Public Const LC_CMD_VIEW_BOTTOM = 431
Public Const LC_CMD_VIEW_LEFT = 432
Public Const LC_CMD_VIEW_RIGHT = 433
Public Const LC_CMD_VIEW_FRONT = 434
Public Const LC_CMD_VIEW_BACK = 435
Public Const LC_CMD_VIEW_SW = 436
Public Const LC_CMD_VIEW_SE = 437
Public Const LC_CMD_VIEW_NE = 438
Public Const LC_CMD_VIEW_NW = 439
Public Const LC_CMD_VIEW_SET = 440
Public Const LC_CMD_LAYER = 501
Public Const LC_CMD_LAYERNF = 502
Public Const LC_CMD_LAYER2 = 502
Public Const LC_CMD_COLOR = 503
Public Const LC_CMD_BCOLOR = 504
Public Const LC_CMD_LINETYPE = 505
Public Const LC_CMD_LWEIGHT = 506
Public Const LC_CMD_TEXTSTYLE = 507
Public Const LC_CMD_BLOCK = 508
Public Const LC_CMD_BLOCKS = 509
Public Const LC_CMD_IMAGE = 510
Public Const LC_CMD_PNTSTYLE = 511
Public Const LC_CMD_DIMSTYLE = 512
Public Const LC_CMD_MLSTYLE = 513
Public Const LC_CMD_LAYOUT = 514
Public Const LC_CMD_LIMITS = 515
Public Const LC_CMD_UNITS = 516
Public Const LC_CMD_DRWPRM = 517
Public Const LC_CMD_SNAP = 105
Public Const LC_CMD_DAIDS = 106
Public Const LC_CMD_GRID = 107
Public Const LC_CMD_POLAR = 108
Public Const LC_CMD_OSNAP = 109
Public Const LC_CMD_OPTIONS = 118
Public Const LC_CMD_PLUGIN = 119
Public Const LC_CMD_REGEN = 120
Public Const LC_CMD_SELOPTS = 122
Public Const LC_CMD_QSELECT = 123
Public Const LC_CMD_DIST = 124
Public Const LC_CMD_AREA = 125
Public Const LC_CMD_SELPGON = 126
Public Const LC_CMD_SELCLAYER = 127
Public Const LC_CMD_SELALL = 128
Public Const LC_CMD_UNSELALL = 129
Public Const LC_CMD_HELP = 1001
Public Const LC_CMD_REPEAT = 1002
Public Const LC_CMD_RESET = 1003
Public Const LC_CMD_SW_GRID = 1011
Public Const LC_CMD_SW_GRIDSNAP = 1012
Public Const LC_CMD_SW_LWEIGHT = 1013
Public Const LC_CMD_SW_OSNAP = 1014
Public Const LC_CMD_SW_POLAR = 1015
Public Const LC_CMD_SW_ORTHO = 1016
Public Const LC_CMD_SNAP_NONE = 1100
Public Const LC_CMD_SNAP_NODE = 1101
Public Const LC_CMD_SNAP_ENDPOINT = 1102
Public Const LC_CMD_SNAP_MIDPOINT = 1103
Public Const LC_CMD_SNAP_CENTER = 1104
Public Const LC_CMD_SNAP_QUADRANT = 1105
Public Const LC_CMD_SNAP_NEAREST = 1106
Public Const LC_CMD_SNAP_INTER = 1107
Public Const LC_CMD_SNAP_PERPEND = 1108
Public Const LC_CMD_SNAP_TANGENT = 1109
Public Const LC_CMD_SNAP_INSERT = 1110
Public Const LC_CMD_SNAP_DIALOG = 1111
Public Const LC_CMD_CUSTOM = 30000
Public Const LC_SNAP_NULL = 0
Public Const LC_SNAP_NODE = 1
Public Const LC_SNAP_ENDPOINT = 2
Public Const LC_SNAP_MIDPOINT = 4
Public Const LC_SNAP_CENTER = 8
Public Const LC_SNAP_NEAREST = 16
Public Const LC_SNAP_INTER = 32
Public Const LC_SNAP_PERPEND = 64
Public Const LC_SNAP_TANGENT = 128
Public Const LC_SNAP_QUADRANT = 256
Public Const LC_SNAP_INSERT = 512
Public Const LC_SNAP_NONE = 1024
Public Const LC_SNAP_ALL = 1023
Public Const LC_SNAP_DBLTANG = 65536
Public Const LC_HELP_DG_LIMITS = 1
Public Const LC_HELP_DG_GRID = 2
Public Const LC_HELP_DG_PSNAP = 3
Public Const LC_HELP_DG_OSNAP = 4
Public Const LC_HELP_DG_OSNAP2 = 5
Public Const LC_HELP_DG_OPTIONS = 6
Public Const LC_HELP_DG_INPUTCOORD = 7
Public Const LC_HELP_DG_LAYERS = 8
Public Const LC_HELP_DG_LAYSTATES = 9
Public Const LC_HELP_DG_TEXTSTYLES = 10
Public Const LC_HELP_DG_PNTSTYLE = 11
Public Const LC_HELP_DG_SELFONT = 13
Public Const LC_HELP_DG_LINETYPES = 14
Public Const LC_HELP_DG_LOADLINETYPE = 15
Public Const LC_HELP_DG_SELLTYPE = 16
Public Const LC_HELP_DG_COLOR = 17
Public Const LC_HELP_DG_TEXT = 18
Public Const LC_HELP_DG_LINEWEIGHT = 19
Public Const LC_HELP_DG_IMAGES = 20
Public Const LC_HELP_DG_IMAGEINSERT = 21
Public Const LC_HELP_DG_BLOCKS = 22
Public Const LC_HELP_DG_INSERT = 23
Public Const LC_HELP_DG_PRINT = 24
Public Const LC_HELP_DG_RASTER = 25
Public Const LC_HELP_DG_LAYOUTS = 26
Public Const LC_HELP_DG_PAGEPROP = 27
Public Const LC_HELP_DG_CREBLOCK = 28
Public Const LC_HELP_DG_SELBLOCK = 29
Public Const LC_HELP_DG_SELTSTYLE = 30
Public Const LC_HELP_DG_ATEXT = 31
Public Const LC_HELP_DG_FONTREPLACE = 32
Public Const LC_HELP_DG_ATTDEF = 33
Public Const LC_HELP_DG_HATCH = 34
Public Const LC_HELP_DG_DRWPROPS = 35
Public Const LC_HELP_DG_UNITS = 36
Public Const LC_HELP_DG_MLSTYLES = 37
Public Const LC_COLOR_RGB = 0
Public Const LC_COLOR_INDEX = 1
Public Const LC_COLOR_RED = 1
Public Const LC_COLOR_YELLOW = 2
Public Const LC_COLOR_GREEN = 3
Public Const LC_COLOR_CYAN = 4
Public Const LC_COLOR_BLUE = 5
Public Const LC_COLOR_MAGENTA = 6
Public Const LC_COLOR_FOREGROUND = 7
Public Const LC_COLOR_GRAY = 8
Public Const LC_COLOR_LTGRAY = 9
Public Const LC_COLOR_BYBLOCK = 0
Public Const LC_COLOR_BYLAYER = 256
Public Const LC_TA_LEFBOT = 0
Public Const LC_TA_CENBOT = 1
Public Const LC_TA_RIGBOT = 2
Public Const LC_TA_LEFCEN = 3
Public Const LC_TA_CENTER = 4
Public Const LC_TA_RIGCEN = 5
Public Const LC_TA_LEFTOP = 6
Public Const LC_TA_CENTOP = 7
Public Const LC_TA_RIGTOP = 8
Public Const LC_TA_ALIGNED = 11
Public Const LC_TA_FIT = 12
Public Const LC_TEXT_BACKWARD = 2
Public Const LC_TEXT_UPDOWN = 4
Public Const LC_ATA_LEFT = 0
Public Const LC_ATA_CENTER = 1
Public Const LC_ATA_RIGHT = 2
Public Const LC_PLFIT_BULGE = 0
Public Const LC_PLFIT_QUAD = 5
Public Const LC_PLFIT_CUBIC = 6
Public Const LC_PLFIT_SPLINE = 99
Public Const LC_PLFIT_ROUND = 101
Public Const LC_PLFIT_LINQUAD = 102
Public Const LC_MLINE_TOP = 0
Public Const LC_MLINE_MIDDLE = 1
Public Const LC_MLINE_BOTTOM = 2
Public Const LC_POINT_PIXEL = 0
Public Const LC_POINT_NONE = 1
Public Const LC_POINT_PLUS = 2
Public Const LC_POINT_X = 3
Public Const LC_POINT_TICK = 4
Public Const LC_POINT_CIRCLE = 32
Public Const LC_POINT_SQUARE = 64
Public Const LC_POINT_RHOMB = 128
Public Const LC_POINT_FILLED = 256
Public Const LC_LEADER_TCENTER = 0
Public Const LC_LEADER_TLEFT = 1
Public Const LC_LEADER_TRIGHT = 2
Public Const LC_LEADER_VERT = 1
Public Const LC_LEADER_CORNER = 2
Public Const LC_ATTRIB_HIDDEN = 1
Public Const LC_ATTRIB_CONST = 2
Public Const LC_ATTRIB_VERIFY = 4
Public Const LC_ATTRIB_PRESET = 8
Public Const LC_ATTRIB_LOCK = 16
Public Const LC_ATTRIB_MTEXT = 32
Public Const LC_DECSEP_POINT = 0
Public Const LC_DECSEP_COMMA = 1
Public Const LC_DECSEP_NONE = 2
Public Const LC_ARROW_CLOSEDF = 0
Public Const LC_ARROW_CLOSEDB = 1
Public Const LC_ARROW_CLOSED = 2
Public Const LC_ARROW_DOT = 3
Public Const LC_ARROW_ARCHTICK = 4
Public Const LC_ARROW_OBLIQUE = 5
Public Const LC_ARROW_OPEN = 6
Public Const LC_ARROW_ORIGIN = 7
Public Const LC_ARROW_ORIGIN2 = 8
Public Const LC_ARROW_OPEN90 = 9
Public Const LC_ARROW_OPEN30 = 10
Public Const LC_ARROW_DOTSMALL = 11
Public Const LC_ARROW_DOTB = 12
Public Const LC_ARROW_DOTSMALLB = 13
Public Const LC_ARROW_BOX = 14
Public Const LC_ARROW_BOXF = 15
Public Const LC_ARROW_DATUM = 16
Public Const LC_ARROW_DATUMF = 17
Public Const LC_ARROW_INTEGRAL = 18
Public Const LC_ARROW_NONE = 19
Public Const LC_PLUG_IMPDRW = 2
Public Const LC_PLUG_EXPDRW = 3
Public Const LC_PLUG_IMGDIB = 4
Public Const LC_FP_FLOAD = 0
Public Const LC_FP_FSAVE = 1
Public Const LC_FP_NITEMS = 2
Public Const LC_FP_ITEM = 3
Public Const LC_DG_SELFILE = 0
Public Const LC_DG_RECENT = 1
Public Const LC_DG_TEMPLATE = 2
Public Const LC_ERR_USERCANCEL = 1
Public Const LC_ERR_OBJTYPE = 2
Public Const LC_ERR_FILENAME = 3
Public Const LC_ERR_FILELOAD = 4
Public Const LC_ERR_FILESAVE = 5
Public Const LC_ERR_NOTAG = 6
Public Const LC_ERR_UNRESBLOCKREF = 7
Public Const LC_ERR_UNRESVIEWREF = 8
Public Const LC_ERR_UNRESHATCH = 9
Public Const LC_ERR_SELBLOCKM = 10
Public Const LC_ERR_SELBLOCKP = 11
Public Const LC_MAX_USERPNT = 100
Public Const LC_PROP_G_REGCODE = 1
Public Const LC_PROP_G_VERSION = 2
Public Const LC_PROP_G_DIRDLL = 3
Public Const LC_PROP_G_DIRCFG = 4
Public Const LC_PROP_G_DIRFONTS = 5
Public Const LC_PROP_G_FILEHATCH = 6
Public Const LC_PROP_G_FILELTYPE = 7
Public Const LC_PROP_G_TEMPLATE = 8
Public Const LC_PROP_G_DIRTEMPLATE = 9
Public Const LC_PROP_G_OWNDXFR = 10
Public Const LC_PROP_G_OWNDXFW = 11
Public Const LC_PROP_G_PANSTEP = 12
Public Const LC_PROP_G_PANFILLING = 13
Public Const LC_PROP_G_PANHATCH = 14
Public Const LC_PROP_G_PANPLWIDTH = 15
Public Const LC_PROP_G_PANLWEIGHT = 16
Public Const LC_PROP_G_PANFILLCHAR = 17
Public Const LC_PROP_G_PANRECTCHAR = 18
Public Const LC_PROP_G_CURSORARROW = 101
Public Const LC_PROP_G_CURSORCROSS = 102
Public Const LC_PROP_G_CURSORSIZE = 103
Public Const LC_PROP_G_AUTOSELECT = 110
Public Const LC_PROP_G_PICKFIRST = 111
Public Const LC_PROP_G_PICKAUTO = 112
Public Const LC_PROP_G_PICKDRAG = 113
Public Const LC_PROP_G_PICKADD = 114
Public Const LC_PROP_G_PICKBOXSIZE = 115
Public Const LC_PROP_G_AUTOUNSELECT = 116
Public Const LC_PROP_G_SELBYLAYER = 117
Public Const LC_PROP_G_SELINSIDE = 118
Public Const LC_PROP_G_ENABLEGRIPS = 119
Public Const LC_PROP_G_GRIPSIZE = 120
Public Const LC_PROP_G_GRIPCOLOR = 121
Public Const LC_PROP_G_GRIPSLIMIT = 122
Public Const LC_PROP_G_SELCOLOR = 123
Public Const LC_PROP_G_DRAGCOLOR = 124
Public Const LC_PROP_G_DLGRECENT = 125
Public Const LC_PROP_G_AXES = 139
Public Const LC_PROP_G_AXESTOP = 140
Public Const LC_PROP_G_GETDELENT = 143
Public Const LC_PROP_G_WNDSTYLE = 144
Public Const LC_PROP_G_OCXSAVECFG = 145
Public Const LC_PROP_G_INITCOUNT = 146
Public Const LC_PROP_G_CMDFONT = 147
Public Const LC_PROP_G_CMDFONTSIZE = 148
Public Const LC_PROP_G_ANGSEPDMS = 149
Public Const LC_PROP_G_ADDRECENT = 150
Public Const LC_PROP_LNG_TAG = 251
Public Const LC_PROP_LNG_STR = 252
Public Const LC_PROP_LNG_STR0 = 253
Public Const LC_PROP_LNG_OLD = 254
Public Const LC_PROP_FONT_FILENAME = 281
Public Const LC_PROP_FONT_NAME = 282
Public Const LC_PROP_FONT_HEIGHT = 283
Public Const LC_PROP_FONT_FILLED = 284
Public Const LC_PROP_FONT_TTF = 285
Public Const LC_PROP_FONT_NCHARS = 286
Public Const LC_PROP_FONT_CHARCODE = 287
Public Const LC_PROP_FONT_CHAR = 288
Public Const LC_PROP_WND_ID = 301
Public Const LC_PROP_WND_VIEW = 302
Public Const LC_PROP_WND_VIEWBLOCK = 303
Public Const LC_PROP_WND_VIEWDRW = 304
Public Const LC_PROP_WND_WIDTH = 306
Public Const LC_PROP_WND_HEIGHT = 307
Public Const LC_PROP_WND_HWND = 308
Public Const LC_PROP_WND_FOCUS = 309
Public Const LC_PROP_WND_EMPTYTEXT = 310
Public Const LC_PROP_WND_CURSORX = 311
Public Const LC_PROP_WND_CURX = 311
Public Const LC_PROP_WND_CURSORY = 312
Public Const LC_PROP_WND_CURY = 312
Public Const LC_PROP_WND_HASBASE = 314
Public Const LC_PROP_WND_BASEX = 315
Public Const LC_PROP_WND_BASEY = 316
Public Const LC_PROP_WND_BASEDIST = 318
Public Const LC_PROP_WND_BASEANGLE = 319
Public Const LC_PROP_WND_HOCX = 321
Public Const LC_PROP_WND_DRAWPICKBOX = 322
Public Const LC_PROP_WND_COMMAND = 323
Public Const LC_PROP_WND_PIXELSIZE = 324
Public Const LC_PROP_WND_PICKBOXSIZE = 325
Public Const LC_PROP_WND_CURLEF = 326
Public Const LC_PROP_WND_CURBOT = 327
Public Const LC_PROP_WND_CURRIG = 328
Public Const LC_PROP_WND_CURTOP = 329
Public Const LC_PROP_DRW_GUID = 401
Public Const LC_PROP_DRW_FILENAME = 402
Public Const LC_PROP_DRW_READONLY = 403
Public Const LC_PROP_DRW_BLOCKX = 404
Public Const LC_PROP_DRW_BLOCKY = 405
Public Const LC_PROP_DRW_BLOCKZ = 406
Public Const LC_PROP_DRW_COLORBACKM = 414
Public Const LC_PROP_DRW_COLORBACKP = 415
Public Const LC_PROP_DRW_COLORFOREM = 416
Public Const LC_PROP_DRW_COLORFOREP = 417
Public Const LC_PROP_DRW_COLORCURSORM = 418
Public Const LC_PROP_DRW_COLORCURSORP = 419
Public Const LC_PROP_DRW_COLORPAPER = 420
Public Const LC_PROP_DRW_COLORPAPER2 = 421
Public Const LC_PROP_DRW_LUNITS = 422
Public Const LC_PROP_DRW_LUPREC = 423
Public Const LC_PROP_DRW_INSUNITS = 424
Public Const LC_PROP_DRW_AUNITS = 425
Public Const LC_PROP_DRW_AUPREC = 426
Public Const LC_PROP_DRW_ANGBASE = 427
Public Const LC_PROP_DRW_ANGDIR = 428
Public Const LC_PROP_DRW_PDMODE = 429
Public Const LC_PROP_DRW_PDSIZE = 430
Public Const LC_PROP_DRW_COLOR = 501
Public Const LC_PROP_DRW_BCOLOR = 502
Public Const LC_PROP_DRW_COLORBYLAYER = 503
Public Const LC_PROP_DRW_COLORBYBLOCK = 504
Public Const LC_PROP_DRW_BCOLORBYLAYER = 505
Public Const LC_PROP_DRW_BCOLORBYBLOCK = 506
Public Const LC_PROP_DRW_COLORI = 507
Public Const LC_PROP_DRW_COLORT = 508
Public Const LC_PROP_DRW_BCOLORI = 509
Public Const LC_PROP_DRW_BCOLORT = 510
Public Const LC_PROP_DRW_LAYER = 511
Public Const LC_PROP_DRW_LINETYPE = 512
Public Const LC_PROP_DRW_LTSCALE = 513
Public Const LC_PROP_DRW_TEXTSTYLE = 514
Public Const LC_PROP_DRW_DIMSTYLE = 515
Public Const LC_PROP_DRW_MLSTYLE = 516
Public Const LC_PROP_DRW_VIEW = 517
Public Const LC_PROP_DRW_LWEIGHT = 518
Public Const LC_PROP_DRW_LWDEFAULT = 519
Public Const LC_PROP_DRW_LWSCALE = 520
Public Const LC_PROP_DRW_LWDISPLAY = 521
Public Const LC_PROP_DRW_SYNCZOOM = 522
Public Const LC_PROP_DRW_DESCR = 559
Public Const LC_PROP_DRW_COMMENT = 559
Public Const LC_PROP_DRW_INT0 = 560
Public Const LC_PROP_DRW_INT1 = 561
Public Const LC_PROP_DRW_INT2 = 562
Public Const LC_PROP_DRW_INT3 = 563
Public Const LC_PROP_DRW_INT4 = 564
Public Const LC_PROP_DRW_INT5 = 565
Public Const LC_PROP_DRW_INT6 = 566
Public Const LC_PROP_DRW_INT7 = 567
Public Const LC_PROP_DRW_INT8 = 568
Public Const LC_PROP_DRW_INT9 = 569
Public Const LC_PROP_DRW_FLOAT0 = 570
Public Const LC_PROP_DRW_FLOAT1 = 571
Public Const LC_PROP_DRW_FLOAT2 = 572
Public Const LC_PROP_DRW_FLOAT3 = 573
Public Const LC_PROP_DRW_FLOAT4 = 574
Public Const LC_PROP_DRW_FLOAT5 = 575
Public Const LC_PROP_DRW_FLOAT6 = 576
Public Const LC_PROP_DRW_FLOAT7 = 577
Public Const LC_PROP_DRW_FLOAT8 = 578
Public Const LC_PROP_DRW_FLOAT9 = 579
Public Const LC_PROP_DRW_STR0 = 580
Public Const LC_PROP_DRW_STR1 = 581
Public Const LC_PROP_DRW_STR2 = 582
Public Const LC_PROP_DRW_STR3 = 583
Public Const LC_PROP_DRW_STR4 = 584
Public Const LC_PROP_DRW_STR5 = 585
Public Const LC_PROP_DRW_STR6 = 586
Public Const LC_PROP_DRW_STR7 = 587
Public Const LC_PROP_DRW_STR8 = 588
Public Const LC_PROP_DRW_STR9 = 589
Public Const LC_PROP_DRW_XDATASIZE = 590
Public Const LC_PROP_DRW_XDATA = 591
Public Const LC_PROP_DRW_HOCX = 598
Public Const LC_PROP_DRW_DIRTY = 599
Public Const LC_PROP_TABLE_ID = 1001
Public Const LC_PROP_TABLE_NAME = 1002
Public Const LC_PROP_TABLE_DESC = 1003
Public Const LC_PROP_TABLE_DESCR = 1003
Public Const LC_PROP_TABLE_DELETED = 1004
Public Const LC_PROP_TABLE_DRW = 1005
Public Const LC_PROP_TABLE_ODHANDLE = 1005
Public Const LC_PROP_TABLE_PRIORITY = 1006
Public Const LC_PROP_TABLE_XDATASIZE = 1007
Public Const LC_PROP_TABLE_XDATA = 1008
Public Const LC_PROP_TABLE_XSTR = 1009
Public Const LC_PROP_TABLE_INT0 = 1010
Public Const LC_PROP_TABLE_INT1 = 1011
Public Const LC_PROP_TABLE_INT2 = 1012
Public Const LC_PROP_TABLE_INT3 = 1013
Public Const LC_PROP_TABLE_INT4 = 1014
Public Const LC_PROP_TABLE_FLOAT0 = 1015
Public Const LC_PROP_TABLE_FLOAT1 = 1016
Public Const LC_PROP_TABLE_FLOAT2 = 1017
Public Const LC_PROP_TABLE_FLOAT3 = 1018
Public Const LC_PROP_TABLE_FLOAT4 = 1019
Public Const LC_PROP_LAYER_ID = 1021
Public Const LC_PROP_LAYER_NAME = 1022
Public Const LC_PROP_LAYER_DESC = 1023
Public Const LC_PROP_LAYER_DELETED = 1024
Public Const LC_PROP_LAYER_COLOR = 1025
Public Const LC_PROP_LAYER_BCOLOR = 1026
Public Const LC_PROP_LAYER_COLORI = 1027
Public Const LC_PROP_LAYER_COLORT = 1028
Public Const LC_PROP_LAYER_BCOLORI = 1029
Public Const LC_PROP_LAYER_BCOLORT = 1030
Public Const LC_PROP_LAYER_LINETYPE = 1031
Public Const LC_PROP_LAYER_LWEIGHT = 1032
Public Const LC_PROP_LAYER_LOCKED = 1033
Public Const LC_PROP_LAYER_NOPRINT = 1034
Public Const LC_PROP_LAYER_VISIBLE = 1035
Public Const LC_PROP_LAYER_0 = 1036
Public Const LC_PROP_LAYER_DRW = 1037
Public Const LC_PROP_LAYER_NODLG = 1038
Public Const LC_PROP_LINETYPE_ID = 1041
Public Const LC_PROP_LINETYPE_NAME = 1042
Public Const LC_PROP_LINETYPE_DESC = 1043
Public Const LC_PROP_LINETYPE_DELETED = 1044
Public Const LC_PROP_LINETYPE_DATA = 1045
Public Const LC_PROP_LINETYPE_SCALE = 1046
Public Const LC_PROP_LINETYPE_CONTINUOUS = 1047
Public Const LC_PROP_LINETYPE_BYLAYER = 1048
Public Const LC_PROP_LINETYPE_BYBLOCK = 1049
Public Const LC_PROP_LINETYPE_STD = 1050
Public Const LC_PROP_LINETYPE_PATLEN = 1051
Public Const LC_PROP_LINETYPE_DRW = 1052
Public Const LC_PROP_LINETYPE_NELEM = 1053
Public Const LC_PROP_LINETYPE_IELEM = 1054
Public Const LC_PROP_LTELEM_LEN = 1055
Public Const LC_PROP_LTELEM_COMPLEX = 1056
Public Const LC_PROP_LTELEM_SHAPE = 1057
Public Const LC_PROP_LTELEM_TEXT = 1058
Public Const LC_PROP_LTELEM_STYLE = 1059
Public Const LC_PROP_LTELEM_FONTNAME = 1060
Public Const LC_PROP_LTELEM_SCALE = 1061
Public Const LC_PROP_LTELEM_ANGLE = 1062
Public Const LC_PROP_LTELEM_ABSANGLE = 1063
Public Const LC_PROP_LTELEM_X = 1064
Public Const LC_PROP_LTELEM_Y = 1065
Public Const LC_PROP_TSTYLE_ID = 1071
Public Const LC_PROP_TSTYLE_NAME = 1072
Public Const LC_PROP_TSTYLE_DESC = 1073
Public Const LC_PROP_TSTYLE_DELETED = 1074
Public Const LC_PROP_TSTYLE_FONT = 1075
Public Const LC_PROP_TSTYLE_HEIGHT = 1076
Public Const LC_PROP_TSTYLE_WSCALE = 1077
Public Const LC_PROP_TSTYLE_OBLIQUE = 1078
Public Const LC_PROP_TSTYLE_ANGLE = 1079
Public Const LC_PROP_TSTYLE_ALIGN = 1080
Public Const LC_PROP_TSTYLE_UPDOWN = 1081
Public Const LC_PROP_TSTYLE_BACKWARD = 1082
Public Const LC_PROP_TSTYLE_LINESPACE = 1083
Public Const LC_PROP_TSTYLE_CHARSPACE = 1084
Public Const LC_PROP_TSTYLE_STANDARD = 1085
Public Const LC_PROP_TSTYLE_SHAPES = 1086
Public Const LC_PROP_TSTYLE_WINFONT = 1087
Public Const LC_PROP_TSTYLE_BOLD = 1088
Public Const LC_PROP_TSTYLE_ITALIC = 1089
Public Const LC_PROP_TSTYLE_UNDERLINE = 1090
Public Const LC_PROP_TSTYLE_STRIKEOUT = 1091
Public Const LC_PROP_TSTYLE_DRW = 1092
Public Const LC_PROP_DIMST_ID = 1101
Public Const LC_PROP_DIMST_NAME = 1102
Public Const LC_PROP_DIMST_DESC = 1103
Public Const LC_PROP_DIMST_DELETED = 1104
Public Const LC_PROP_DIMST_STANDARD = 1114
Public Const LC_PROP_DIMST_DRW = 1115
Public Const LC_PROP_DIMST_TSTYLE = 1116
Public Const LC_PROP_BLOCK_ID = 1131
Public Const LC_PROP_BLOCK_NAME = 1132
Public Const LC_PROP_BLOCK_DESC = 1133
Public Const LC_PROP_BLOCK_DELETED = 1134
Public Const LC_PROP_BLOCK_X = 1135
Public Const LC_PROP_BLOCK_Y = 1136
Public Const LC_PROP_BLOCK_Z = 1137
Public Const LC_PROP_BLOCK_UFSCALING = 1138
Public Const LC_PROP_BLOCK_UNITS = 1139
Public Const LC_PROP_BLOCK_UNITSCALE = 1140
Public Const LC_PROP_BLOCK_MODEL = 1141
Public Const LC_PROP_BLOCK_PAPER = 1142
Public Const LC_PROP_BLOCK_LAYOUT = 1143
Public Const LC_PROP_BLOCK_STANDARD = 1144
Public Const LC_PROP_BLOCK_HIDDEN = 1145
Public Const LC_PROP_BLOCK_DIM = 1146
Public Const LC_PROP_BLOCK_HATCH = 1147
Public Const LC_PROP_BLOCK_DRW = 1148
Public Const LC_PROP_BLOCK_NOBJ = 1149
Public Const LC_PROP_BLOCK_NSELOBJ = 1150
Public Const LC_PROP_BLOCK_ATTRIBS = 1157
Public Const LC_PROP_BLOCK_BASE = 1159
Public Const LC_PROP_VIEW_ID = 1161
Public Const LC_PROP_VIEW_NAME = 1162
Public Const LC_PROP_VIEW_DESC = 1163
Public Const LC_PROP_VIEW_DELETED = 1164
Public Const LC_PROP_VIEW_BLOCK = 1165
Public Const LC_PROP_VIEW_MODEL = 1166
Public Const LC_PROP_VIEW_PAPER = 1168
Public Const LC_PROP_VIEW_XMIN = 1173
Public Const LC_PROP_VIEW_YMIN = 1174
Public Const LC_PROP_VIEW_XMAX = 1175
Public Const LC_PROP_VIEW_YMAX = 1176
Public Const LC_PROP_VIEW_LEF = 1177
Public Const LC_PROP_VIEW_BOT = 1178
Public Const LC_PROP_VIEW_RIG = 1179
Public Const LC_PROP_VIEW_TOP = 1180
Public Const LC_PROP_VIEW_PIXELSIZE = 1181
Public Const LC_PROP_VIEW_PICKBOXSIZE = 1182
Public Const LC_PROP_VIEW_LIMITS = 1185
Public Const LC_PROP_VIEW_COLORBACK = 1186
Public Const LC_PROP_VIEW_COLORFORE = 1187
Public Const LC_PROP_VIEW_COLORCURSOR = 1188
Public Const LC_PROP_VIEW_GRID = 1191
Public Const LC_PROP_VIEW_GRIDSNAP = 1192
Public Const LC_PROP_VIEW_OSNAP = 1193
Public Const LC_PROP_VIEW_OSNAPMODE = 1194
Public Const LC_PROP_VIEW_PTRACK = 1195
Public Const LC_PROP_VIEW_ORTHO = 1196
Public Const LC_PROP_VIEW_ORDER = 1230
Public Const LC_PROP_VIEW_DRW = 1231
Public Const LC_PROP_PAPER_SIZE = 1241
Public Const LC_PROP_PAPER_ORIENT = 1242
Public Const LC_PROP_PAPER_W = 1243
Public Const LC_PROP_PAPER_H = 1244
Public Const LC_PROP_PAPER_X0 = 1245
Public Const LC_PROP_PAPER_Y0 = 1246
Public Const LC_PROP_PAPER_INCH = 1247
Public Const LC_PROP_IMAGE_ID = 1301
Public Const LC_PROP_IMAGE_NAME = 1302
Public Const LC_PROP_IMAGE_DESC = 1303
Public Const LC_PROP_IMAGE_DELETED = 1304
Public Const LC_PROP_IMAGE_FILENAME = 1305
Public Const LC_PROP_IMAGE_SIZE = 1306
Public Const LC_PROP_IMAGE_WPIX = 1307
Public Const LC_PROP_IMAGE_HPIX = 1308
Public Const LC_PROP_IMAGE_CBIT = 1309
Public Const LC_PROP_IMAGE_DRW = 1310
Public Const LC_PROP_ENT_ID = 3001
Public Const LC_PROP_ENT_KEY = 3002
Public Const LC_PROP_ENT_COLOR = 3003
Public Const LC_PROP_ENT_BCOLOR = 3004
Public Const LC_PROP_ENT_COLORBYLAYER = 3005
Public Const LC_PROP_ENT_COLORBYBLOCK = 3006
Public Const LC_PROP_ENT_BCOLORBYLAYER = 3007
Public Const LC_PROP_ENT_BCOLORBYBLOCK = 3008
Public Const LC_PROP_ENT_COLORI = 3009
Public Const LC_PROP_ENT_COLORT = 3010
Public Const LC_PROP_ENT_BCOLORI = 3011
Public Const LC_PROP_ENT_BCOLORT = 3012
Public Const LC_PROP_ENT_LAYER = 3013
Public Const LC_PROP_ENT_LINETYPE = 3014
Public Const LC_PROP_ENT_LTSCALE = 3015
Public Const LC_PROP_ENT_LWEIGHT = 3016
Public Const LC_PROP_ENT_BLOCK = 3017
Public Const LC_PROP_ENT_DRW = 3018
Public Const LC_PROP_ENT_BORDER = 3019
Public Const LC_PROP_ENT_LOCKED = 3020
Public Const LC_PROP_ENT_FILLED = 3021
Public Const LC_PROP_ENT_VISIBLE = 3022
Public Const LC_PROP_ENT_HIDDEN = 3023
Public Const LC_PROP_ENT_BLINK = 3024
Public Const LC_PROP_ENT_TYPE = 3025
Public Const LC_PROP_ENT_DELETED = 3026
Public Const LC_PROP_ENT_IMMORTAL = 3027
Public Const LC_PROP_ENT_SELECTED = 3028
Public Const LC_PROP_ENT_PRIORITY = 3029
Public Const LC_PROP_ENT_XDATASIZE = 3031
Public Const LC_PROP_ENT_XDATA = 3032
Public Const LC_PROP_ENT_XSTR = 3033
Public Const LC_PROP_ENT_XGUID = 3034
Public Const LC_PROP_ENT_Z = 3035
Public Const LC_PROP_POINT_X = 3102
Public Const LC_PROP_POINT_Y = 3103
Public Const LC_PROP_POINT_OWNSTYLE = 3105
Public Const LC_PROP_POINT_SIZE = 3106
Public Const LC_PROP_POINT_MODE = 3107
Public Const LC_PROP_POINT_BORDER = 3108
Public Const LC_PROP_POINT_POS = 3109
Public Const LC_PROP_LINE_X0 = 3121
Public Const LC_PROP_LINE_Y0 = 3122
Public Const LC_PROP_LINE_X1 = 3124
Public Const LC_PROP_LINE_Y1 = 3125
Public Const LC_PROP_LINE_DX = 3127
Public Const LC_PROP_LINE_DY = 3128
Public Const LC_PROP_LINE_ANG = 3130
Public Const LC_PROP_LINE_LEN = 3131
Public Const LC_PROP_LINE_START = 3132
Public Const LC_PROP_LINE_END = 3133
Public Const LC_PROP_XLINE_X0 = 3141
Public Const LC_PROP_XLINE_Y0 = 3142
Public Const LC_PROP_XLINE_ANG = 3144
Public Const LC_PROP_XLINE_DIRX = 3145
Public Const LC_PROP_XLINE_DIRY = 3146
Public Const LC_PROP_XLINE_RAY = 3147
Public Const LC_PROP_XLINE_BASE = 3148
Public Const LC_PROP_CIRCLE_X = 3201
Public Const LC_PROP_CIRCLE_Y = 3202
Public Const LC_PROP_CIRCLE_RAD = 3204
Public Const LC_PROP_CIRCLE_DIAM = 3205
Public Const LC_PROP_CIRCLE_LEN = 3206
Public Const LC_PROP_CIRCLE_AREA = 3207
Public Const LC_PROP_CIRCLE_FILLED = 3208
Public Const LC_PROP_CIRCLE_BORDER = 3209
Public Const LC_PROP_CIRCLE_CENTER = 3210
Public Const LC_PROP_ARC_X = 3231
Public Const LC_PROP_ARC_Y = 3232
Public Const LC_PROP_ARC_RAD = 3234
Public Const LC_PROP_ARC_ANG0 = 3235
Public Const LC_PROP_ARC_ANGARC = 3236
Public Const LC_PROP_ARC_ANGEND = 3237
Public Const LC_PROP_ARC_X0 = 3238
Public Const LC_PROP_ARC_Y0 = 3239
Public Const LC_PROP_ARC_XEND = 3241
Public Const LC_PROP_ARC_YEND = 3242
Public Const LC_PROP_ARC_LEN = 3244
Public Const LC_PROP_ARC_CHLEN = 3245
Public Const LC_PROP_ARC_AREA = 3246
Public Const LC_PROP_ARC_FILLED = 3247
Public Const LC_PROP_ARC_BORDER = 3248
Public Const LC_PROP_ARC_SECTOR = 3249
Public Const LC_PROP_ARC_CENTER = 3250
Public Const LC_PROP_ELL_X = 3261
Public Const LC_PROP_ELL_Y = 3262
Public Const LC_PROP_ELL_R1 = 3264
Public Const LC_PROP_ELL_R2 = 3265
Public Const LC_PROP_ELL_ANGLE = 3266
Public Const LC_PROP_ELL_ANG0 = 3267
Public Const LC_PROP_ELL_ANGARC = 3268
Public Const LC_PROP_ELL_ANGEND = 3269
Public Const LC_PROP_ELL_X0 = 3270
Public Const LC_PROP_ELL_Y0 = 3271
Public Const LC_PROP_ELL_XEND = 3273
Public Const LC_PROP_ELL_YEND = 3274
Public Const LC_PROP_ELL_LEN = 3276
Public Const LC_PROP_ELL_AREA = 3277
Public Const LC_PROP_ELL_FILLED = 3278
Public Const LC_PROP_ELL_BORDER = 3279
Public Const LC_PROP_ELL_SECTOR = 3280
Public Const LC_PROP_ELL_CENTER = 3281
Public Const LC_PROP_PLINE_FIT = 3301
Public Const LC_PROP_PLINE_NVERS = 3302
Public Const LC_PROP_PLINE_NPATHS = 3303
Public Const LC_PROP_PLINE_WIDTH = 3305
Public Const LC_PROP_PLINE_RADIUS = 3306
Public Const LC_PROP_PLINE_CHAMFER = 3307
Public Const LC_PROP_PLINE_LEN = 3308
Public Const LC_PROP_PLINE_AREA = 3309
Public Const LC_PROP_PLINE_CLOSED = 3310
Public Const LC_PROP_PLINE_FILLED = 3311
Public Const LC_PROP_PLINE_BORDER = 3312
Public Const LC_PROP_PLINE_HASANG0 = 3313
Public Const LC_PROP_PLINE_ANG0 = 3314
Public Const LC_PROP_PLINE_HASANG2 = 3315
Public Const LC_PROP_PLINE_ANG2 = 3316
Public Const LC_PROP_MLINE_STYLE = 3351
Public Const LC_PROP_MLINE_JUST = 3352
Public Const LC_PROP_MLINE_SCALE = 3353
Public Const LC_PROP_MLINE_NVERS = 3354
Public Const LC_PROP_MLINE_CLOSED = 3355
Public Const LC_PROP_MLINE_FIT = 3356
Public Const LC_PROP_MLINE_LEN = 3357
Public Const LC_PROP_MLINE_AREA = 3358
Public Const LC_PROP_RECT_X = 3371
Public Const LC_PROP_RECT_Y = 3372
Public Const LC_PROP_RECT_W = 3374
Public Const LC_PROP_RECT_H = 3375
Public Const LC_PROP_RECT_ANGLE = 3376
Public Const LC_PROP_RECT_RAD = 3377
Public Const LC_PROP_RECT_CHAMFER = 3378
Public Const LC_PROP_RECT_FILLED = 3379
Public Const LC_PROP_RECT_BORDER = 3380
Public Const LC_PROP_RECT_LEN = 3381
Public Const LC_PROP_RECT_AREA = 3382
Public Const LC_PROP_RECT_CENTER = 3383
Public Const LC_PROP_TEXT_STYLE = 3401
Public Const LC_PROP_TEXT_STR = 3402
Public Const LC_PROP_TEXT_LEN = 3403
Public Const LC_PROP_TEXT_ALIGN = 3404
Public Const LC_PROP_TEXT_X = 3405
Public Const LC_PROP_TEXT_Y = 3406
Public Const LC_PROP_TEXT_H = 3411
Public Const LC_PROP_TEXT_WSCALE = 3412
Public Const LC_PROP_TEXT_ANGLE = 3413
Public Const LC_PROP_TEXT_OBLIQUE = 3414
Public Const LC_PROP_TEXT_CHARSPACE = 3415
Public Const LC_PROP_TEXT_WRECT = 3416
Public Const LC_PROP_TEXT_X0 = 3417
Public Const LC_PROP_TEXT_Y0 = 3418
Public Const LC_PROP_TEXT_XFIT = 3419
Public Const LC_PROP_TEXT_YFIT = 3420
Public Const LC_PROP_TEXT_UPDOWN = 3421
Public Const LC_PROP_TEXT_BACKWARD = 3422
Public Const LC_PROP_TEXT_POS = 3423
Public Const LC_PROP_TEXT_FIT = 3424
Public Const LC_PROP_TEXTW_STYLE = 3431
Public Const LC_PROP_TEXTW_STR = 3432
Public Const LC_PROP_TEXTW_LEN = 3433
Public Const LC_PROP_TEXTW_ALIGN = 3434
Public Const LC_PROP_TEXTW_X = 3435
Public Const LC_PROP_TEXTW_Y = 3436
Public Const LC_PROP_TEXTW_H = 3438
Public Const LC_PROP_TEXTW_PIXH = 3439
Public Const LC_PROP_TEXTW_LABEL = 3439
Public Const LC_PROP_TEXTW_DX = 3440
Public Const LC_PROP_TEXTW_DY = 3441
Public Const LC_PROP_TEXTW_WSCALE = 3442
Public Const LC_PROP_TEXTW_ANGLE = 3443
Public Const LC_PROP_TEXTW_POS = 3444
Public Const LC_PROP_TEXTW_OFFSET = 3445
Public Const LC_PROP_MTEXT_STYLE = 3451
Public Const LC_PROP_MTEXT_STR = 3452
Public Const LC_PROP_MTEXT_LEN = 3453
Public Const LC_PROP_MTEXT_ALIGN = 3454
Public Const LC_PROP_MTEXT_X = 3455
Public Const LC_PROP_MTEXT_Y = 3456
Public Const LC_PROP_MTEXT_H = 3458
Public Const LC_PROP_MTEXT_WSCALE = 3459
Public Const LC_PROP_MTEXT_ANGLE = 3460
Public Const LC_PROP_MTEXT_OBLIQUE = 3461
Public Const LC_PROP_MTEXT_WRECT = 3462
Public Const LC_PROP_MTEXT_HRECT = 3463
Public Const LC_PROP_MTEXT_WRAPWIDTH = 3464
Public Const LC_PROP_MTEXT_LINESPACE = 3465
Public Const LC_PROP_MTEXT_CHARSPACE = 3466
Public Const LC_PROP_MTEXT_MIRROR = 3467
Public Const LC_PROP_MTEXT_POS = 3468
Public Const LC_PROP_ATEXT_STYLE = 3481
Public Const LC_PROP_ATEXT_STR = 3482
Public Const LC_PROP_ATEXT_LEN = 3483
Public Const LC_PROP_ATEXT_X = 3484
Public Const LC_PROP_ATEXT_Y = 3485
Public Const LC_PROP_ATEXT_RADIUS = 3487
Public Const LC_PROP_ATEXT_ANGLE = 3488
Public Const LC_PROP_ATEXT_CW = 3489
Public Const LC_PROP_ATEXT_H = 3490
Public Const LC_PROP_ATEXT_WSCALE = 3491
Public Const LC_PROP_ATEXT_CHARSPACE = 3492
Public Const LC_PROP_ATEXT_ALIGN = 3493
Public Const LC_PROP_ATEXT_POS = 3494
Public Const LC_PROP_ATT_MODE = 3501
Public Const LC_PROP_ATT_STYLE = 3502
Public Const LC_PROP_ATT_TAG = 3503
Public Const LC_PROP_ATT_PROMPT = 3504
Public Const LC_PROP_ATT_VALUE = 3505
Public Const LC_PROP_ATT_ALIGN = 3506
Public Const LC_PROP_ATT_X = 3507
Public Const LC_PROP_ATT_Y = 3508
Public Const LC_PROP_ATT_Z = 3509
Public Const LC_PROP_ATT_H = 3510
Public Const LC_PROP_ATT_WSCALE = 3511
Public Const LC_PROP_ATT_ANGLE = 3512
Public Const LC_PROP_ATT_OBLIQUE = 3513
Public Const LC_PROP_ATT_X0 = 3514
Public Const LC_PROP_ATT_Y0 = 3515
Public Const LC_PROP_ATT_XFIT = 3516
Public Const LC_PROP_ATT_YFIT = 3517
Public Const LC_PROP_ATT_UPDOWN = 3518
Public Const LC_PROP_ATT_BACKWARD = 3519
Public Const LC_PROP_ATT_POS = 3520
Public Const LC_PROP_ATT_FIT = 3521
Public Const LC_PROP_BLKREF_BLOCK = 3531
Public Const LC_PROP_BLKREF_X = 3532
Public Const LC_PROP_BLKREF_Y = 3533
Public Const LC_PROP_BLKREF_SCALE = 3535
Public Const LC_PROP_BLKREF_SCX = 3536
Public Const LC_PROP_BLKREF_SCY = 3537
Public Const LC_PROP_BLKREF_UFSCALE = 3539
Public Const LC_PROP_BLKREF_ANGLE = 3540
Public Const LC_PROP_BLKREF_ATTRIBS = 3541
Public Const LC_PROP_BLKREF_POS = 3542
Public Const LC_PROP_IMGREF_IMAGE = 3551
Public Const LC_PROP_IMGREF_X = 3552
Public Const LC_PROP_IMGREF_Y = 3553
Public Const LC_PROP_IMGREF_XC = 3554
Public Const LC_PROP_IMGREF_YC = 3555
Public Const LC_PROP_IMGREF_W = 3556
Public Const LC_PROP_IMGREF_H = 3557
Public Const LC_PROP_IMGREF_SCALE = 3558
Public Const LC_PROP_IMGREF_SCX = 3559
Public Const LC_PROP_IMGREF_SCY = 3560
Public Const LC_PROP_IMGREF_ANGLE = 3561
Public Const LC_PROP_IMGREF_UFSCALE = 3562
Public Const LC_PROP_IMGREF_BORDER = 3563
Public Const LC_PROP_IMGREF_POS = 3564
Public Const LC_PROP_IMGREF_PATH = 3566
Public Const LC_PROP_VPORT_LEF = 3603
Public Const LC_PROP_VPORT_BOT = 3604
Public Const LC_PROP_VPORT_RIG = 3605
Public Const LC_PROP_VPORT_TOP = 3606
Public Const LC_PROP_VPORT_W = 3607
Public Const LC_PROP_VPORT_H = 3608
Public Const LC_PROP_VPORT_VX = 3609
Public Const LC_PROP_VPORT_VY = 3610
Public Const LC_PROP_VPORT_VSCALE = 3611
Public Const LC_PROP_VPORT_VANGLE = 3612
Public Const LC_PROP_VPORT_FIXSCALE = 3613
Public Const LC_PROP_VPORT_NFL = 3614
Public Const LC_PROP_VPORT_RECT = 3615
Public Const LC_PROP_VPORT_VRECT = 3616
Public Const LC_PROP_HATCH_NAME = 3631
Public Const LC_PROP_HATCH_PATTERN = 3632
Public Const LC_PROP_HATCH_SCALE = 3633
Public Const LC_PROP_HATCH_ANGLE = 3634
Public Const LC_PROP_HATCH_SIZE = 3635
Public Const LC_PROP_HATCH_ASSOC = 3636
Public Const LC_PROP_HATCH_SOLID = 3637
Public Const LC_PROP_HATCH_CUSTOM = 3638
Public Const LC_PROP_HATCH_NPT = 3639
Public Const LC_PROP_HATCH_NLOOP = 3640
Public Const LC_PROP_HATCH_NHPL = 3641
Public Const LC_PROP_HATCH_IHPL = 3642
Public Const LC_PROP_HPL_ANGLE = 3651
Public Const LC_PROP_HPL_X0 = 3652
Public Const LC_PROP_HPL_Y0 = 3653
Public Const LC_PROP_HPL_DX = 3654
Public Const LC_PROP_HPL_DY = 3655
Public Const LC_PROP_HPL_NDASH = 3656
Public Const LC_PROP_HPL_DASH1 = 3657
Public Const LC_PROP_HPL_DASH2 = 3658
Public Const LC_PROP_HPL_DASH3 = 3659
Public Const LC_PROP_HPL_DASH4 = 3660
Public Const LC_PROP_HPL_DASH5 = 3661
Public Const LC_PROP_HPL_DASH6 = 3662
Public Const LC_PROP_HPL_DASH7 = 3663
Public Const LC_PROP_HPL_DASH8 = 3664
Public Const LC_PROP_ECW_FILENAME = 3901
Public Const LC_PROP_ECW_LOADED = 3902
Public Const LC_PROP_ECW_XMIN = 3903
Public Const LC_PROP_ECW_YMIN = 3904
Public Const LC_PROP_ECW_XMAX = 3905
Public Const LC_PROP_ECW_YMAX = 3906
Public Const LC_PROP_ECW_W = 3907
Public Const LC_PROP_ECW_H = 3908
Public Const LC_PROP_ECW_WPIX = 3909
Public Const LC_PROP_ECW_HPIX = 3910
Public Const LC_PROP_ECW_CBIT = 3911
Public Const LC_PROP_ECW_SCALEX = 3912
Public Const LC_PROP_ECW_SCALEY = 3913
Public Const LC_PROP_ECW_BORDER = 3914
Public Const LC_PROP_DIM_STYLE = 4001
Public Const LC_PROP_DIM_MEAS = 4003
Public Const LC_PROP_DIM_TEXT = 4004
Public Const LC_PROP_DIMANG_STYLE = 4001
Public Const LC_PROP_DIMANG_Z = 4002
Public Const LC_PROP_DIMANG_MEAS = 4003
Public Const LC_PROP_DIMANG_TEXT = 4004
Public Const LC_PROP_DIMALI_STYLE = 4001
Public Const LC_PROP_DIMALI_MEAS = 4003
Public Const LC_PROP_DIMALI_TEXT = 4004
Public Const LC_PROP_DIMDIA_STYLE = 4001
Public Const LC_PROP_DIMDIA_MEAS = 4003
Public Const LC_PROP_DIMDIA_TEXT = 4004
Public Const LC_PROP_DIMRAD_STYLE = 4001
Public Const LC_PROP_DIMRAD_MEAS = 4003
Public Const LC_PROP_DIMRAD_TEXT = 4004
Public Const LC_PROP_DIMORD_STYLE = 4001
Public Const LC_PROP_DIMORD_MEAS = 4003
Public Const LC_PROP_DIMORD_TEXT = 4004
Public Const LC_PROP_DIMROT_STYLE = 4001
Public Const LC_PROP_DIMROT_MEAS = 4003
Public Const LC_PROP_DIMROT_TEXT = 4004
Public Const LC_PROP_DIMANG_CPX = 4021
Public Const LC_PROP_DIMANG_CPY = 4022
Public Const LC_PROP_DIMANG_DP1X = 4023
Public Const LC_PROP_DIMANG_DP1Y = 4024
Public Const LC_PROP_DIMANG_DP2X = 4025
Public Const LC_PROP_DIMANG_DP2Y = 4026
Public Const LC_PROP_DIMANG_DP3X = 4027
Public Const LC_PROP_DIMANG_DP3Y = 4028
Public Const LC_PROP_DIMANG_DP4X = 4029
Public Const LC_PROP_DIMANG_DP4Y = 4030
Public Const LC_PROP_DIMANG_APX = 4031
Public Const LC_PROP_DIMANG_APY = 4032
Public Const LC_PROP_DIMANG_EXT1 = 4033
Public Const LC_PROP_DIMANG_EXT2 = 4034
Public Const LC_PROP_DIMANG_RAD = 4035
Public Const LC_PROP_DIMANG_TPOS = 4036
Public Const LC_PROP_DIMANG_CP = 4037
Public Const LC_PROP_DIMANG_DP1 = 4038
Public Const LC_PROP_DIMANG_DP2 = 4039
Public Const LC_PROP_DIMANG_DP3 = 4040
Public Const LC_PROP_DIMANG_DP4 = 4041
Public Const LC_PROP_DIMANG_AP = 4042
Public Const LC_PROP_DIMANG_TP = 4043
Public Const LC_PROP_DIMALI_DP1X = 4051
Public Const LC_PROP_DIMALI_DP1Y = 4052
Public Const LC_PROP_DIMALI_DP2X = 4053
Public Const LC_PROP_DIMALI_DP2Y = 4054
Public Const LC_PROP_DIMALI_TPX = 4055
Public Const LC_PROP_DIMALI_TPY = 4056
Public Const LC_PROP_DIMALI_DP1 = 4057
Public Const LC_PROP_DIMALI_DP2 = 4058
Public Const LC_PROP_DIMALI_TP = 4059
Public Const LC_PROP_DIMDIA_CPX = 4071
Public Const LC_PROP_DIMDIA_CPY = 4072
Public Const LC_PROP_DIMDIA_RPX = 4073
Public Const LC_PROP_DIMDIA_RPY = 4074
Public Const LC_PROP_DIMDIA_TPX = 4075
Public Const LC_PROP_DIMDIA_TPY = 4076
Public Const LC_PROP_DIMDIA_CP = 4077
Public Const LC_PROP_DIMDIA_RP = 4078
Public Const LC_PROP_DIMDIA_TP = 4079
Public Const LC_PROP_DIMRAD_CPX = 4086
Public Const LC_PROP_DIMRAD_CPY = 4087
Public Const LC_PROP_DIMRAD_RPX = 4088
Public Const LC_PROP_DIMRAD_RPY = 4089
Public Const LC_PROP_DIMRAD_TPX = 4090
Public Const LC_PROP_DIMRAD_TPY = 4091
Public Const LC_PROP_DIMRAD_CP = 4092
Public Const LC_PROP_DIMRAD_RP = 4093
Public Const LC_PROP_DIMRAD_TP = 4094
Public Const LC_PROP_DIMORD_XORD = 4101
Public Const LC_PROP_DIMORD_DPX = 4102
Public Const LC_PROP_DIMORD_DPY = 4103
Public Const LC_PROP_DIMORD_TPX = 4104
Public Const LC_PROP_DIMORD_TPY = 4105
Public Const LC_PROP_DIMORD_DP = 4106
Public Const LC_PROP_DIMORD_TP = 4107
Public Const LC_PROP_DIMROT_ANGLE = 4121
Public Const LC_PROP_DIMROT_DP1X = 4122
Public Const LC_PROP_DIMROT_DP1Y = 4123
Public Const LC_PROP_DIMROT_DP2X = 4124
Public Const LC_PROP_DIMROT_DP2Y = 4125
Public Const LC_PROP_DIMROT_TPX = 4126
Public Const LC_PROP_DIMROT_TPY = 4127
Public Const LC_PROP_DIMROT_DP1 = 4128
Public Const LC_PROP_DIMROT_DP2 = 4129
Public Const LC_PROP_DIMROT_TP = 4130
Public Const LC_PROP_LEADER_STYLE = 4502
Public Const LC_PROP_LEADER_TEXT = 4503
Public Const LC_PROP_LEADER_ALIGN = 4504
Public Const LC_PROP_LEADER_TPX = 4505
Public Const LC_PROP_LEADER_TPY = 4506
Public Const LC_PROP_LEADER_APX = 4507
Public Const LC_PROP_LEADER_APY = 4508
Public Const LC_PROP_LEADER_LDIST = 4510
Public Const LC_PROP_LEADER_VERT = 4511
Public Const LC_PROP_LEADER_CORNER = 4512
Public Const LC_PROP_LEADER_ATTACH = 4513
Public Const LC_PROP_LEADER_TP = 4514
Public Const LC_PROP_LEADER_AP = 4515
Public Const LC_PROP_VER_X = 5001
Public Const LC_PROP_VER_Y = 5002
Public Const LC_PROP_VER_Z = 5003
Public Const LC_PROP_VER_ENDPATH = 5005
Public Const LC_PROP_VER_FIX = 5006
Public Const LC_PROP_VER_RADIUS = 5007
Public Const LC_PROP_VER_W0 = 5011
Public Const LC_PROP_VER_W1 = 5012
Public Const LC_PROP_VER_SEGDX = 5013
Public Const LC_PROP_VER_SEGDY = 5014
Public Const LC_PROP_VER_SEGANG = 5015
Public Const LC_PROP_VER_SEGLEN = 5016
Public Const LC_PROP_VER_BULGE = 5021
Public Const LC_PROP_VER_POS = 5031
Public Const LC_PROP_VER_PRM = 5032
Public Const LC_PROP_CMD_ID = 5102
Public Const LC_PROP_CMD_STEP = 5103
Public Const LC_PROP_CMD_LCWND = 5104
Public Const LC_PROP_CMD_HWND = 5105
Public Const LC_PROP_CMD_DRW = 5106
Public Const LC_PROP_CMD_BLOCK = 5107
Public Const LC_PROP_CMD_VIEW = 5108
Public Const LC_PROP_CMD_CURSORX = 5109
Public Const LC_PROP_CMD_CURX = 5109
Public Const LC_PROP_CMD_CURSORY = 5110
Public Const LC_PROP_CMD_CURY = 5110
Public Const LC_PROP_CMD_PIXELSIZE = 5111
Public Const LC_PROP_CMD_PICKBOXSIZE = 5112
Public Const LC_PROP_CMD_CURLEF = 5113
Public Const LC_PROP_CMD_CURBOT = 5114
Public Const LC_PROP_CMD_CURRIG = 5115
Public Const LC_PROP_CMD_CURTOP = 5116
Public Const LC_PROP_CMD_OSNAP = 5117
Public Const LC_PROP_CMD_OSNAPONCE = 5118
Public Const LC_PROP_CMD_NPOINTS = 5119
Public Const LC_PROP_CMD_INT0 = 5120
Public Const LC_PROP_CMD_INT1 = 5121
Public Const LC_PROP_CMD_INT2 = 5122
Public Const LC_PROP_CMD_INT3 = 5123
Public Const LC_PROP_CMD_INT4 = 5124
Public Const LC_PROP_CMD_INT5 = 5125
Public Const LC_PROP_CMD_INT6 = 5126
Public Const LC_PROP_CMD_INT7 = 5127
Public Const LC_PROP_CMD_INT8 = 5128
Public Const LC_PROP_CMD_INT9 = 5129
Public Const LC_PROP_CMD_FLOAT0 = 5130
Public Const LC_PROP_CMD_FLOAT1 = 5131
Public Const LC_PROP_CMD_FLOAT2 = 5132
Public Const LC_PROP_CMD_FLOAT3 = 5133
Public Const LC_PROP_CMD_FLOAT4 = 5134
Public Const LC_PROP_CMD_FLOAT5 = 5135
Public Const LC_PROP_CMD_FLOAT6 = 5136
Public Const LC_PROP_CMD_FLOAT7 = 5137
Public Const LC_PROP_CMD_FLOAT8 = 5138
Public Const LC_PROP_CMD_FLOAT9 = 5139
Public Const LC_PROP_CMD_HAND0 = 5140
Public Const LC_PROP_CMD_HAND1 = 5141
Public Const LC_PROP_CMD_HAND2 = 5142
Public Const LC_PROP_CMD_HAND3 = 5143
Public Const LC_PROP_CMD_HAND4 = 5144
Public Const LC_PROP_CMD_HAND5 = 5145
Public Const LC_PROP_CMD_HAND6 = 5146
Public Const LC_PROP_CMD_HAND7 = 5147
Public Const LC_PROP_CMD_HAND8 = 5148
Public Const LC_PROP_CMD_HAND9 = 5149
Public Const LC_PROP_CMD_STR = 5150
Public Const LC_PROP_CMDWND_ENABLE = 9001
Public Const LC_PROP_PROPWND_ENABLE = 9002
Public Const LC_PROP_PROPWND_DIVCOEF = 9003
Public Const LC_MOD_ENT_PROP = 1
Public Const LC_MOD_ENT_SET = 2
Public Const LC_MOD_PLINE_ADDVER = 4
Public Const LC_MOD_PLINE_INSVER = 5
Public Const LC_MOD_PLINE_DELVER = 6
Public Const LC_MOD_PLINE_REVERSE = 7
Public Const LC_MOD_MLINE_ADDVER = 14
Public Const LC_MOD_MLINE_INSVER = 15
Public Const LC_MOD_MLINE_DELVER = 16
Public Const LC_MOD_MLINE_REVERSE = 17
Public Const LC_MOD_ENT_MOVE = 20
Public Const LC_MOD_ENT_ROTATE = 21
Public Const LC_MOD_ENT_SCALE = 22
Public Const LC_MOD_ENT_MIRROR = 23
Public Const LC_MOD_ENT_JOIN = 24
Public Const LC_MOD_OBJ_PROP = 31
Public Const LC_MOD_BLOCK_PURGE = 32
Public Const LC_MOD_BLOCK_ADDENT = 33
Public Const LC_MOD_DRW_PROP = 51

Public Declare Function lcInitialize Lib "Litecad.dll" (ByVal szConfigDir As String) As Long
Public Declare Function lcUninitialize Lib "Litecad.dll" (ByVal bSaveConfig As Long) As Long
Public Declare Function lcCfgGetValue Lib "Litecad.dll" (ByVal hCfg As Long, ByVal szTag As String) As String
Public Declare Function lcCfgSetValue Lib "Litecad.dll" (ByVal hCfg As Long, ByVal szTagValue As String) As Long
Public Declare Function lcAddFontRes Lib "Litecad.dll" (ByVal hModule As Long, ByVal idResource As Long, ByVal szFontName As String) As Long
Public Declare Function lcAddFontFile Lib "Litecad.dll" (ByVal szFilename As String, ByVal szFontName As String) As Long
Public Declare Function lcAddFontBin Lib "Litecad.dll" (ByVal hData As Long, ByVal szFontName As String) As Long
Public Declare Function lcStrAdd Lib "Litecad.dll" (ByVal szTag As String, ByVal szText As String) As Long
Public Declare Function lcStrSet Lib "Litecad.dll" (ByVal szTag As String, ByVal szText As String) As Long
Public Declare Function lcStrGet Lib "Litecad.dll" (ByVal szTag As String) As String
Public Declare Function lcStrFileLoad Lib "Litecad.dll" (ByVal szFileName As String) As Long
Public Declare Function lcStrFileSave Lib "Litecad.dll" (ByVal szFileName As String, ByVal szLanguage As String, ByVal bInit As Long) As Long
Public Declare Function lcPropGetBool Lib "Litecad.dll" (ByVal hObject As Long, ByVal idProp As Long) As Long
Public Declare Function lcPropGetInt Lib "Litecad.dll" (ByVal hObject As Long, ByVal idProp As Long) As Long
Public Declare Function lcPropGetFloat Lib "Litecad.dll" (ByVal hObject As Long, ByVal idProp As Long) As Double
Public Declare Function lcPropGetStr Lib "Litecad.dll" (ByVal hObject As Long, ByVal idProp As Long) As String
Public Declare Function lcPropGetHandle Lib "Litecad.dll" (ByVal hObject As Long, ByVal idProp As Long) As Long
Public Declare Function lcPropPutBool Lib "Litecad.dll" (ByVal hObject As Long, ByVal idProp As Long, ByVal bValue As Long) As Long
Public Declare Function lcPropPutInt Lib "Litecad.dll" (ByVal hObject As Long, ByVal idProp As Long, ByVal Value As Long) As Long
Public Declare Function lcPropPutFloat Lib "Litecad.dll" (ByVal hObject As Long, ByVal idProp As Long, ByVal Value As Double) As Long
Public Declare Function lcPropPutStr Lib "Litecad.dll" (ByVal hObject As Long, ByVal idProp As Long, ByVal szValue As String) As Long
Public Declare Function lcPropPutHandle Lib "Litecad.dll" (ByVal hObject As Long, ByVal idProp As Long, ByVal hValue As Long) As Long
Public Declare Function lcCreateDrawing Lib "Litecad.dll" () As Long
Public Declare Function lcDeleteDrawing Lib "Litecad.dll" (ByVal hDrw As Long) As Long
Public Declare Function lcDrwNew Lib "Litecad.dll" (ByVal hDrw As Long, ByVal szFileName As String, ByVal hLcWnd As Long) As Long
Public Declare Function lcDrwNewT Lib "Litecad.dll" (ByVal hDrw As Long, ByVal szFileName As String, ByVal szTemplate As String, ByVal hLcWnd As Long) As Long
Public Declare Function lcDrwLoad Lib "Litecad.dll" (ByVal hDrw As Long, ByVal szFileName As String, ByVal hWnd As Long, ByVal hLcWnd As Long) As Long
Public Declare Function lcDrwSave Lib "Litecad.dll" (ByVal hDrw As Long, ByVal szFileName As String, ByVal bBak As Long, ByVal hWnd As Long) As Long
Public Declare Function lcDrwPurge Lib "Litecad.dll" (ByVal hDrw As Long) As Long
Public Declare Function lcDrwRegenViews Lib "Litecad.dll" (ByVal hDrw As Long, ByVal hEnt As Long) As Long
Public Declare Function lcDrwSortObjects Lib "Litecad.dll" (ByVal hDrw As Long, ByVal ObjType As Long) As Long
Public Declare Function lcDrwClearXData Lib "Litecad.dll" (ByVal hDrw As Long, ByVal ObjType As Long, ByVal Mode As Long) As Long
Public Declare Function lcDrwResolveBlocks Lib "Litecad.dll" (ByVal hDrw As Long, ByVal szError As Any) As Long
Public Declare Function lcDrwAddLayer Lib "Litecad.dll" (ByVal hDrw As Long, ByVal szName As String, ByVal szColor As String, ByVal hLtype As Long, ByVal Lweight As Long) As Long
Public Declare Function lcDrwAddLinetype Lib "Litecad.dll" (ByVal hDrw As Long, ByVal szName As String, ByVal szDefinition As String) As Long
Public Declare Function lcDrwAddLinetypeF Lib "Litecad.dll" (ByVal hDrw As Long, ByVal szName As String, ByVal szFileName As String, ByVal szLtypeName As String) As Long
Public Declare Function lcDrwAddTextStyle Lib "Litecad.dll" (ByVal hDrw As Long, ByVal szName As String, ByVal szFontName As String) As Long
Public Declare Function lcDrwAddDimStyle Lib "Litecad.dll" (ByVal hDrw As Long, ByVal szName As String) As Long
Public Declare Function lcDrwAddImage Lib "Litecad.dll" (ByVal hDrw As Long, ByVal szName As String, ByVal szFileName As String) As Long
Public Declare Function lcDrwAddBlock Lib "Litecad.dll" (ByVal hDrw As Long, ByVal szName As String, ByVal X As Double, ByVal Y As Double) As Long
Public Declare Function lcDrwAddBlockFromFile Lib "Litecad.dll" (ByVal hDrw As Long, ByVal szName As String, ByVal szFileName As String, ByVal Overwrite As Long, ByVal hwParent As Long) As Long
Public Declare Function lcDrwAddBlockFromDrw Lib "Litecad.dll" (ByVal hDrw As Long, ByVal szName As String, ByVal hDrw2 As Long, ByVal Overwrite As Long, ByVal hwParent As Long) As Long
Public Declare Function lcDrwAddBlockFile Lib "Litecad.dll" (ByVal hDrw As Long, ByVal szName As String, ByVal szFileName As String, ByVal Overwrite As Long, ByVal hwParent As Long) As Long
Public Declare Function lcDrwAddViewPaper Lib "Litecad.dll" (ByVal hDrw As Long, ByVal szName As String, ByVal PaperSize As Long, ByVal Orient As Long, ByVal Width As Double, ByVal Height As Double) As Long
Public Declare Function lcDrwDeleteObject Lib "Litecad.dll" (ByVal hDrw As Long, ByVal hObject As Long) As Long
Public Declare Function lcDrwGetFirstObject Lib "Litecad.dll" (ByVal hDrw As Long, ByVal ObjType As Long) As Long
Public Declare Function lcDrwGetNextObject Lib "Litecad.dll" (ByVal hDrw As Long, ByVal hObject As Long) As Long
Public Declare Function lcDrwGetObjectByID Lib "Litecad.dll" (ByVal hDrw As Long, ByVal ObjType As Long, ByVal Id As Long) As Long
Public Declare Function lcDrwGetObjectByIDH Lib "Litecad.dll" (ByVal hDrw As Long, ByVal ObjType As Long, ByVal szId As String) As Long
Public Declare Function lcDrwGetObjectByName Lib "Litecad.dll" (ByVal hDrw As Long, ByVal ObjType As Long, ByVal szName As String) As Long
Public Declare Function lcDrwCountObjects Lib "Litecad.dll" (ByVal hDrw As Long, ByVal ObjType As Long) As Long
Public Declare Function lcDrwGetViewByBlock Lib "Litecad.dll" (ByVal hDrw As Long, ByVal hBlock As Long) As Long
Public Declare Function lcDrwGetEntByID Lib "Litecad.dll" (ByVal hDrw As Long, ByVal Id As Long) As Long
Public Declare Function lcDrwGetEntByIDH Lib "Litecad.dll" (ByVal hDrw As Long, ByVal szId As String) As Long
Public Declare Function lcDrwGetEntByKey Lib "Litecad.dll" (ByVal hDrw As Long, ByVal Key As Long) As Long
Public Declare Function lcViewSetRect Lib "Litecad.dll" (ByVal hView As Long, ByVal Xcen As Double, ByVal Ycen As Double, ByVal Width As Double, ByVal Height As Double) As Long
Public Declare Function lcViewSetRect2 Lib "Litecad.dll" (ByVal hView As Long, ByVal Lef As Double, ByVal Bot As Double, ByVal Rig As Double, ByVal Top As Double) As Long
Public Declare Function lcViewSetLimits Lib "Litecad.dll" (ByVal hView As Long, ByVal Xmin As Double, ByVal Ymin As Double, ByVal Xmax As Double, ByVal Ymax As Double) As Long
Public Declare Function lcViewSetGrid Lib "Litecad.dll" (ByVal hView As Long, ByVal X0 As Double, ByVal Y0 As Double, ByVal dX As Double, ByVal dY As Double) As Long
Public Declare Function lcViewRegen Lib "Litecad.dll" (ByVal hView As Long, ByVal hEnt As Long) As Long
Public Declare Function lcViewSetPaperSize Lib "Litecad.dll" (ByVal hView As Long, ByVal PaperSize As Long, ByVal Orient As Long, ByVal Width As Double, ByVal Height As Double) As Long
Public Declare Function lcViewGetEntByPoint Lib "Litecad.dll" (ByVal hView As Long, ByVal X As Double, ByVal Y As Double, ByVal Delta As Double, ByVal Mode As Long) As Long
Public Declare Function lcViewGetEntsByRect Lib "Litecad.dll" (ByVal hView As Long, ByVal Lef As Double, ByVal Bot As Double, ByVal Rig As Double, ByVal Top As Double, ByVal bCross As Long, ByVal MaxNum As Long) As Long
Public Declare Function lcViewGetEntity Lib "Litecad.dll" (ByVal iEnt As Long) As Long
Public Declare Function lcViewRasterize Lib "Litecad.dll" (ByVal hView As Long, ByVal szFileName As String, ByVal Lef As Double, ByVal Bot As Double, ByVal Rig As Double, ByVal Top As Double, ByVal Scale As Double) As Long
Public Declare Function lcViewDrawMarker Lib "Litecad.dll" (ByVal hView As Long, ByVal X As Double, ByVal Y As Double) As Long
Public Declare Function lcViewDrawLine Lib "Litecad.dll" (ByVal hView As Long, ByVal X0 As Double, ByVal Y0 As Double, ByVal X1 As Double, ByVal Y1 As Double) As Long
Public Declare Function lcViewDrawXline Lib "Litecad.dll" (ByVal hView As Long, ByVal X0 As Double, ByVal Y0 As Double, ByVal X1 As Double, ByVal Y1 As Double, ByVal bRay As Long) As Long
Public Declare Function lcViewDrawRect Lib "Litecad.dll" (ByVal hView As Long, ByVal X0 As Double, ByVal Y0 As Double, ByVal X1 As Double, ByVal Y1 As Double) As Long
Public Declare Function lcBlockClear Lib "Litecad.dll" (ByVal hBlock As Long, ByVal hLayer As Long) As Long
Public Declare Function lcBlockPurge Lib "Litecad.dll" (ByVal hBlock As Long) As Long
Public Declare Function lcBlockSortEnts Lib "Litecad.dll" (ByVal hBlock As Long) As Long
Public Declare Function lcBlockAddPoint Lib "Litecad.dll" (ByVal hBlock As Long, ByVal X As Double, ByVal Y As Double) As Long
Public Declare Function lcBlockAddPoint2 Lib "Litecad.dll" (ByVal hBlock As Long, ByVal X As Double, ByVal Y As Double, ByVal PtMode As Long, ByVal PtSize As Double) As Long
Public Declare Function lcBlockAddXline Lib "Litecad.dll" (ByVal hBlock As Long, ByVal X As Double, ByVal Y As Double, ByVal Angle As Double, ByVal bRay As Long) As Long
Public Declare Function lcBlockAddXline2P Lib "Litecad.dll" (ByVal hBlock As Long, ByVal X As Double, ByVal Y As Double, ByVal X2 As Double, ByVal Y2 As Double, ByVal bRay As Long) As Long
Public Declare Function lcBlockAddLine Lib "Litecad.dll" (ByVal hBlock As Long, ByVal X1 As Double, ByVal Y1 As Double, ByVal X2 As Double, ByVal Y2 As Double) As Long
Public Declare Function lcBlockAddLineDir Lib "Litecad.dll" (ByVal hBlock As Long, ByVal X As Double, ByVal Y As Double, ByVal Angle As Double, ByVal Dist As Double) As Long
Public Declare Function lcBlockAddLineTan Lib "Litecad.dll" (ByVal hBlock As Long, ByVal hEnt1 As Long, ByVal hEnt2 As Long, ByVal Mode As Long) As Long
Public Declare Function lcBlockAddPolyline Lib "Litecad.dll" (ByVal hBlock As Long, ByVal FitType As Long, ByVal bClosed As Long, ByVal bFilled As Long) As Long
Public Declare Function lcBlockAddRect Lib "Litecad.dll" (ByVal hBlock As Long, ByVal Xc As Double, ByVal Yc As Double, ByVal Width As Double, ByVal Height As Double, ByVal Angle As Double, ByVal bFilled As Long) As Long
Public Declare Function lcBlockAddRect2 Lib "Litecad.dll" (ByVal hBlock As Long, ByVal Left As Double, ByVal Bottom As Double, ByVal Width As Double, ByVal Height As Double, ByVal Rad As Double, ByVal bFilled As Long) As Long
Public Declare Function lcBlockAddCircle Lib "Litecad.dll" (ByVal hBlock As Long, ByVal X As Double, ByVal Y As Double, ByVal Radius As Double, ByVal bFilled As Long) As Long
Public Declare Function lcBlockAddArc Lib "Litecad.dll" (ByVal hBlock As Long, ByVal X As Double, ByVal Y As Double, ByVal Radius As Double, ByVal StartAngle As Double, ByVal ArcAngle As Double) As Long
Public Declare Function lcBlockAddArc3P Lib "Litecad.dll" (ByVal hBlock As Long, ByVal X1 As Double, ByVal Y1 As Double, ByVal X2 As Double, ByVal Y2 As Double, ByVal X3 As Double, ByVal Y3 As Double) As Long
Public Declare Function lcBlockAddEllipse Lib "Litecad.dll" (ByVal hBlock As Long, ByVal X As Double, ByVal Y As Double, ByVal R1 As Double, ByVal R2 As Double, ByVal RotAngle As Double, ByVal StartAngle As Double, ByVal ArcAngle As Double) As Long
Public Declare Function lcBlockAddText Lib "Litecad.dll" (ByVal hBlock As Long, ByVal szText As String, ByVal X As Double, ByVal Y As Double) As Long
Public Declare Function lcBlockAddText2 Lib "Litecad.dll" (ByVal hBlock As Long, ByVal szText As String, ByVal X As Double, ByVal Y As Double, ByVal Align As Long, ByVal H As Double, ByVal WScale As Double, ByVal RotAngle As Double, ByVal Oblique As Double) As Long
Public Declare Function lcBlockAddTextWin Lib "Litecad.dll" (ByVal hBlock As Long, ByVal szText As String, ByVal X As Double, ByVal Y As Double) As Long
Public Declare Function lcBlockAddTextWin2 Lib "Litecad.dll" (ByVal hBlock As Long, ByVal szText As String, ByVal X As Double, ByVal Y As Double, ByVal Align As Long, ByVal H As Double, ByVal WScale As Double, ByVal RotAngle As Double, ByVal Oblique As Double) As Long
Public Declare Function lcBlockAddMText Lib "Litecad.dll" (ByVal hBlock As Long, ByVal szText As String, ByVal X As Double, ByVal Y As Double, ByVal WrapWidth As Double, ByVal Align As Long, ByVal RotAngle As Double, ByVal H As Double, ByVal WScale As Double) As Long
Public Declare Function lcBlockAddArcText Lib "Litecad.dll" (ByVal hBlock As Long, ByVal szText As String, ByVal X As Double, ByVal Y As Double, ByVal Radius As Double, ByVal StartAngle As Double, ByVal bClockwise As Long, ByVal H As Double, ByVal WScale As Double) As Long
Public Declare Function lcBlockAddBlockRef Lib "Litecad.dll" (ByVal hBlock As Long, ByVal hRefBlock As Long, ByVal X As Double, ByVal Y As Double, ByVal Scal As Double, ByVal Angle As Double) As Long
Public Declare Function lcBlockAddBlockRefID Lib "Litecad.dll" (ByVal hBlock As Long, ByVal idRefBlock As Long, ByVal X As Double, ByVal Y As Double, ByVal Scal As Double, ByVal Angle As Double) As Long
Public Declare Function lcBlockAddBlockRefIDH Lib "Litecad.dll" (ByVal hBlock As Long, ByVal szIdRefBlock As String, ByVal X As Double, ByVal Y As Double, ByVal Scal As Double, ByVal Angle As Double) As Long
Public Declare Function lcBlockAddImageRef Lib "Litecad.dll" (ByVal hBlock As Long, ByVal hImage As Long, ByVal X As Double, ByVal Y As Double, ByVal Width As Double, ByVal Height As Double, ByVal bBorder As Long) As Long
Public Declare Function lcBlockAddEcw Lib "Litecad.dll" (ByVal hBlock As Long, ByVal szFileName As String) As Long
Public Declare Function lcBlockAddAttDef Lib "Litecad.dll" (ByVal hBlock As Long, ByVal Mode As Long, ByVal szTag As String, ByVal szPrompt As String, ByVal szDefVal As String, ByVal X As Double, ByVal Y As Double, ByVal Align As Long, ByVal H As Double, ByVal WScale As Double, ByVal RotAngle As Double, ByVal Oblique As Double) As Long
Public Declare Function lcBlockAddHatch Lib "Litecad.dll" (ByVal hBlock As Long, ByVal szFileName As String, ByVal szPatName As String, ByVal Scal As Double, ByVal Angle As Double) As Long
Public Declare Function lcBlockAddViewport Lib "Litecad.dll" (ByVal hBlock As Long, ByVal Lef As Double, ByVal Bot As Double, ByVal Width As Double, ByVal Height As Double, ByVal DrwPntX As Double, ByVal DrwPntY As Double, ByVal DrwScale As Double, ByVal DrwAngle As Double) As Long
Public Declare Function lcBlockAddLeader Lib "Litecad.dll" (ByVal hBlock As Long, ByVal szText As String, ByVal Xt As Double, ByVal Yt As Double, ByVal LandDist As Double, ByVal Xa As Double, ByVal Ya As Double, ByVal Attach As Long, ByVal Align As Long) As Long
Public Declare Function lcBlockAddDimRot Lib "Litecad.dll" (ByVal hBlock As Long, ByVal X0 As Double, ByVal Y0 As Double, ByVal X1 As Double, ByVal Y1 As Double, ByVal Xt As Double, ByVal Yt As Double, ByVal Angle As Double, ByVal szText As String) As Long
Public Declare Function lcBlockAddDimHor Lib "Litecad.dll" (ByVal hBlock As Long, ByVal X0 As Double, ByVal Y0 As Double, ByVal X1 As Double, ByVal Y1 As Double, ByVal Yt As Double, ByVal szText As String) As Long
Public Declare Function lcBlockAddDimVer Lib "Litecad.dll" (ByVal hBlock As Long, ByVal X0 As Double, ByVal Y0 As Double, ByVal X1 As Double, ByVal Y1 As Double, ByVal Xt As Double, ByVal szText As String) As Long
Public Declare Function lcBlockAddDimAli Lib "Litecad.dll" (ByVal hBlock As Long, ByVal X0 As Double, ByVal Y0 As Double, ByVal X1 As Double, ByVal Y1 As Double, ByVal Xt As Double, ByVal Yt As Double, ByVal szText As String) As Long
Public Declare Function lcBlockAddDimAli2 Lib "Litecad.dll" (ByVal hBlock As Long, ByVal X0 As Double, ByVal Y0 As Double, ByVal X1 As Double, ByVal Y1 As Double, ByVal Dt As Double, ByVal szText As String) As Long
Public Declare Function lcBlockAddDimOrd Lib "Litecad.dll" (ByVal hBlock As Long, ByVal Xd As Double, ByVal Yd As Double, ByVal Xt As Double, ByVal Yt As Double, ByVal bX As Long, ByVal szText As String) As Long
Public Declare Function lcBlockAddDimRad Lib "Litecad.dll" (ByVal hBlock As Long, ByVal Xc As Double, ByVal Yc As Double, ByVal Xr As Double, ByVal Yr As Double, ByVal Xt As Double, ByVal Yt As Double, ByVal szText As String) As Long
Public Declare Function lcBlockAddDimRad2 Lib "Litecad.dll" (ByVal hBlock As Long, ByVal Xc As Double, ByVal Yc As Double, ByVal R As Double, ByVal Angle As Double, ByVal TextOff As Double, ByVal szText As String) As Long
Public Declare Function lcBlockAddDimDia Lib "Litecad.dll" (ByVal hBlock As Long, ByVal Xc As Double, ByVal Yc As Double, ByVal Xr As Double, ByVal Yr As Double, ByVal Xt As Double, ByVal Yt As Double, ByVal szText As String) As Long
Public Declare Function lcBlockAddDimDia2 Lib "Litecad.dll" (ByVal hBlock As Long, ByVal Xc As Double, ByVal Yc As Double, ByVal R As Double, ByVal Angle As Double, ByVal TextOff As Double, ByVal szText As String) As Long
Public Declare Function lcBlockAddDimAng Lib "Litecad.dll" (ByVal hBlock As Long, ByVal Xc As Double, ByVal Yc As Double, ByVal X1 As Double, ByVal Y1 As Double, ByVal X2 As Double, ByVal Y2 As Double, ByVal Xa As Double, ByVal Ya As Double, ByVal TextPos As Double, ByVal szText As String) As Long
Public Declare Function lcBlockAddDimAng2 Lib "Litecad.dll" (ByVal hBlock As Long, ByVal X1 As Double, ByVal Y1 As Double, ByVal X2 As Double, ByVal Y2 As Double, ByVal X3 As Double, ByVal Y3 As Double, ByVal X4 As Double, ByVal Y4 As Double, ByVal Xa As Double, ByVal Ya As Double, ByVal TextPos As Double, ByVal szText As String) As Long
Public Declare Function lcBlockGetFirstEnt Lib "Litecad.dll" (ByVal hBlock As Long) As Long
Public Declare Function lcBlockGetNextEnt Lib "Litecad.dll" (ByVal hBlock As Long, ByVal hEnt As Long) As Long
Public Declare Function lcBlockGetLastEnt Lib "Litecad.dll" (ByVal hBlock As Long) As Long
Public Declare Function lcBlockGetPrevEnt Lib "Litecad.dll" (ByVal hBlock As Long, ByVal hEnt As Long) As Long
Public Declare Function lcBlockGetEntByID Lib "Litecad.dll" (ByVal hBlock As Long, ByVal Id As Long) As Long
Public Declare Function lcBlockGetEntByIDH Lib "Litecad.dll" (ByVal hBlock As Long, ByVal szId As String) As Long
Public Declare Function lcBlockGetEntByKey Lib "Litecad.dll" (ByVal hBlock As Long, ByVal Key As Long) As Long
Public Declare Function lcBlockUnselect Lib "Litecad.dll" (ByVal hBlock As Long) As Long
Public Declare Function lcBlockSelectEnt Lib "Litecad.dll" (ByVal hBlock As Long, ByVal hEntity As Long, ByVal bSelect As Long) As Long
Public Declare Function lcBlockSelErase Lib "Litecad.dll" (ByVal hBlock As Long) As Long
Public Declare Function lcBlockSelMove Lib "Litecad.dll" (ByVal hBlock As Long, ByVal dX As Double, ByVal dY As Double, ByVal bCopy As Long, ByVal bNewSelect As Long) As Long
Public Declare Function lcBlockSelScale Lib "Litecad.dll" (ByVal hBlock As Long, ByVal X0 As Double, ByVal Y0 As Double, ByVal Scal As Double, ByVal bCopy As Long, ByVal bNewSelect As Long) As Long
Public Declare Function lcBlockSelRotate Lib "Litecad.dll" (ByVal hBlock As Long, ByVal X0 As Double, ByVal Y0 As Double, ByVal Angle As Double, ByVal bCopy As Long, ByVal bNewSelect As Long) As Long
Public Declare Function lcBlockSelMirror Lib "Litecad.dll" (ByVal hBlock As Long, ByVal X1 As Double, ByVal Y1 As Double, ByVal X2 As Double, ByVal Y2 As Double, ByVal bCopy As Long, ByVal bNewSelect As Long) As Long
Public Declare Function lcBlockSelExplode Lib "Litecad.dll" (ByVal hBlock As Long) As Long
Public Declare Function lcBlockSelJoin Lib "Litecad.dll" (ByVal hBlock As Long, ByVal Delta As Double) As Long
Public Declare Function lcBlockGetFirstSel Lib "Litecad.dll" (ByVal hBlock As Long) As Long
Public Declare Function lcBlockGetNextSel Lib "Litecad.dll" (ByVal hBlock As Long) As Long
Public Declare Function lcEntErase Lib "Litecad.dll" (ByVal hEnt As Long, ByVal bErase As Long) As Long
Public Declare Function lcEntMove Lib "Litecad.dll" (ByVal hEnt As Long, ByVal dX As Double, ByVal dY As Double) As Long
Public Declare Function lcEntScale Lib "Litecad.dll" (ByVal hEnt As Long, ByVal X0 As Double, ByVal Y0 As Double, ByVal Scal As Double) As Long
Public Declare Function lcEntRotate Lib "Litecad.dll" (ByVal hEnt As Long, ByVal X0 As Double, ByVal Y0 As Double, ByVal Angle As Double) As Long
Public Declare Function lcEntMirror Lib "Litecad.dll" (ByVal hEnt As Long, ByVal X1 As Double, ByVal Y1 As Double, ByVal X2 As Double, ByVal Y2 As Double) As Long
Public Declare Function lcEntExplode Lib "Litecad.dll" (ByVal hEnt As Long, ByVal bSelect As Long) As Long
Public Declare Function lcEntOffset Lib "Litecad.dll" (ByVal hEnt As Long, ByVal Dist As Double) As Long
Public Declare Function lcEntToTop Lib "Litecad.dll" (ByVal hEnt As Long) As Long
Public Declare Function lcEntToBottom Lib "Litecad.dll" (ByVal hEnt As Long) As Long
Public Declare Function lcEntToAbove Lib "Litecad.dll" (ByVal hEnt As Long, ByVal hEnt2 As Long) As Long
Public Declare Function lcEntToUnder Lib "Litecad.dll" (ByVal hEnt As Long, ByVal hEnt2 As Long) As Long
Public Declare Function lcEntGetGrip Lib "Litecad.dll" (ByVal hEnt As Long, ByVal iGrip As Long, ByVal pX As Long, ByVal pY As Long) As Long
Public Declare Function lcEntPutGrip Lib "Litecad.dll" (ByVal hEnt As Long, ByVal iGrip As Long, ByVal X As Double, ByVal Y As Double) As Long
Public Declare Function lcEntUpdate Lib "Litecad.dll" (ByVal hEnt As Long) As Long
Public Declare Function lcIntersection Lib "Litecad.dll" (ByVal hEnt As Long, ByVal hEnt2 As Long) As Long
Public Declare Function lcInterGetPoint Lib "Litecad.dll" (ByVal iPoint As Long, ByVal pX As Long, ByVal pY As Long) As Long
Public Declare Function lcPlineAddVer Lib "Litecad.dll" (ByVal hPline As Long, ByVal hVer0 As Long, ByVal X As Double, ByVal Y As Double) As Long
Public Declare Function lcPlineAddVer2 Lib "Litecad.dll" (ByVal hPline As Long, ByVal hVer0 As Long, ByVal X As Double, ByVal Y As Double, ByVal Param As Double, ByVal W0 As Double, ByVal W1 As Double) As Long
Public Declare Function lcPlineAddVerDir Lib "Litecad.dll" (ByVal hPline As Long, ByVal hVer0 As Long, ByVal Ang As Double, ByVal Len As Double) As Long
Public Declare Function lcPlineDeleteVer Lib "Litecad.dll" (ByVal hPline As Long, ByVal hVer As Long) As Long
Public Declare Function lcPlineGetFirstVer Lib "Litecad.dll" (ByVal hPline As Long) As Long
Public Declare Function lcPlineGetNextVer Lib "Litecad.dll" (ByVal hPline As Long, ByVal hVer As Long) As Long
Public Declare Function lcPlineGetLastVer Lib "Litecad.dll" (ByVal hPline As Long) As Long
Public Declare Function lcPlineGetPrevVer Lib "Litecad.dll" (ByVal hPline As Long, ByVal hVer As Long) As Long
Public Declare Function lcPlineGetVer Lib "Litecad.dll" (ByVal hPline As Long, ByVal Index As Long) As Long
Public Declare Function lcPlineGetVerPt Lib "Litecad.dll" (ByVal hPline As Long, ByVal X As Double, ByVal Y As Double, ByVal Delta As Double) As Long
Public Declare Function lcPlineGetSeg Lib "Litecad.dll" (ByVal hPline As Long, ByVal X As Double, ByVal Y As Double, ByVal Delta As Double) As Long
Public Declare Function lcPlineReverse Lib "Litecad.dll" (ByVal hPline As Long) As Long
Public Declare Function lcVportSetView Lib "Litecad.dll" (ByVal hVport As Long, ByVal Xcen As Double, ByVal Ycen As Double, ByVal Scale As Double, ByVal Angle As Double) As Long
Public Declare Function lcVportFrolClear Lib "Litecad.dll" (ByVal hVport As Long) As Long
Public Declare Function lcVportFrolAdd Lib "Litecad.dll" (ByVal hVport As Long, ByVal hLayer As Long) As Long
Public Declare Function lcVportFrolGet Lib "Litecad.dll" (ByVal hVport As Long, ByVal iLayer As Long) As Long
Public Declare Function lcVportIsFrol Lib "Litecad.dll" (ByVal hVport As Long, ByVal hLayer As Long) As Long
Public Declare Function lcBlkRefAddAtt Lib "Litecad.dll" (ByVal hBlockRef As Long, ByVal szTag As String, ByVal szValue As String) As Long
Public Declare Function lcBlkRefGetFirstAtt Lib "Litecad.dll" (ByVal hBlockRef As Long) As Long
Public Declare Function lcBlkRefGetNextAtt Lib "Litecad.dll" (ByVal hBlockRef As Long, ByVal hAttrib As Long) As Long
Public Declare Function lcBlkRefGetAtt Lib "Litecad.dll" (ByVal hBlockRef As Long, ByVal szTag As String) As Long
Public Declare Function lcHatchBoundStart Lib "Litecad.dll" (ByVal hHatch As Long) As Long
Public Declare Function lcHatchBoundPoint Lib "Litecad.dll" (ByVal hHatch As Long, ByVal X As Double, ByVal Y As Double) As Long
Public Declare Function lcHatchBoundEndLoop Lib "Litecad.dll" (ByVal hHatch As Long) As Long
Public Declare Function lcHatchBoundEnd Lib "Litecad.dll" (ByVal hHatch As Long) As Long
Public Declare Function lcHatchPatStart Lib "Litecad.dll" (ByVal hHatch As Long) As Long
Public Declare Function lcHatchPatLine Lib "Litecad.dll" (ByVal hHatch As Long, ByVal Angle As Double, ByVal x0 As Double, ByVal y0 As Double, ByVal dx As Double, ByVal dy As Double, ByVal nDash As Long, ByVal L0 As Double, ByVal L1 As Double, ByVal L2 As Double, ByVal L3 As Double, ByVal L4 As Double, ByVal L5 As Double, ByVal L6 As Double, ByVal L7 As Double) As Long
Public Declare Function lcHatchPatEnd Lib "Litecad.dll" (ByVal hHatch As Long) As Long
Public Declare Function lcHatchGetLoopSize Lib "Litecad.dll" (ByVal hHatch As Long, ByVal iLoop As Long) As Long
Public Declare Function lcHatchGetPoint Lib "Litecad.dll" (ByVal hHatch As Long, ByVal iPnt As Long, ByVal pX As Long, ByVal pY As Long) As Long
Public Declare Function lcRectGetPolyline Lib "Litecad.dll" (ByVal hRect As Long, ByVal pX As Long, ByVal pY As Long, ByVal pBulge As Long) As Long
Public Declare Function lcXlinePutDir Lib "Litecad.dll" (ByVal hXline As Long, ByVal X As Double, ByVal Y As Double) As Long
Public Declare Function lcCreateWindow Lib "Litecad.dll" (ByVal hWndParent As Long, ByVal Style As Long, ByVal Left As Long, ByVal Top As Long, ByVal Width As Long, ByVal Height As Long) As Long
Public Declare Function lcDeleteWindow Lib "Litecad.dll" (ByVal hLcWnd As Long) As Long
Public Declare Function lcWndResize Lib "Litecad.dll" (ByVal hLcWnd As Long, ByVal Left As Long, ByVal Top As Long, ByVal Width As Long, ByVal Height As Long) As Long
Public Declare Function lcWndSelectView Lib "Litecad.dll" (ByVal hLcWnd As Long, ByVal hView As Long) As Long
Public Declare Function lcWndZoomRect Lib "Litecad.dll" (ByVal hLcWnd As Long, ByVal Left As Double, ByVal Bottom As Double, ByVal Right As Double, ByVal Top As Double) As Long
Public Declare Function lcWndZoomScale Lib "Litecad.dll" (ByVal hLcWnd As Long, ByVal Scal As Double) As Long
Public Declare Function lcWndRedraw Lib "Litecad.dll" (ByVal hLcWnd As Long) As Long
Public Declare Function lcWndSetFocus Lib "Litecad.dll" (ByVal hLcWnd As Long) As Long
Public Declare Function lcWndExeCommand Lib "Litecad.dll" (ByVal hLcWnd As Long, ByVal Command As Long, ByVal CmdParam As Long) As Long
Public Declare Function lcWndCoordFromDrw Lib "Litecad.dll" (ByVal hLcWnd As Long, ByVal Xdrw As Double, ByVal Ydrw As Double, ByVal pXwin As Long, ByVal pYwin As Long) As Long
Public Declare Function lcWndCoordToDrw Lib "Litecad.dll" (ByVal hLcWnd As Long, ByVal Xwin As Long, ByVal Ywin As Long, ByVal pXdrw As Long, ByVal pYdrw As Long) As Long
Public Declare Function lcWndGetCursorCoord Lib "Litecad.dll" (ByVal hLcWnd As Long, ByVal pXwin As Long, ByVal pYwin As Long, ByVal pXdrw As Long, ByVal pYdrw As Long) As Long
Public Declare Function lcWndGetEntByPoint Lib "Litecad.dll" (ByVal hLcWnd As Long, ByVal Xwin As Long, ByVal Ywin As Long) As Long
Public Declare Function lcWndSetCmdwin Lib "Litecad.dll" (ByVal hLcWnd As Long, ByVal hCmdLine As Long) As Long
Public Declare Function lcWndSetPropwin Lib "Litecad.dll" (ByVal hLcWnd As Long, ByVal hPropWnd As Long) As Long
Public Declare Function lcWndOnClose Lib "Litecad.dll" (ByVal hLcWnd As Long) As Long
Public Declare Function lcWndGetPoint Lib "Litecad.dll" (ByVal hLcWnd As Long, ByVal szPrompt As String, ByVal SnapMode As Long, ByVal Index As Long, ByVal pX As Long, ByVal pY As Long) As Long
Public Declare Function lcWndGetPointBuf Lib "Litecad.dll" (ByVal hLcWnd As Long, ByVal Index As Long, ByVal pX As Long, ByVal pY As Long) As Long
Public Declare Function lcCoordDrwToWnd Lib "Litecad.dll" (ByVal hLcWnd As Long, ByVal Xdrw As Double, ByVal Ydrw As Double, ByVal pXwin As Long, ByVal pYwin As Long) As Long
Public Declare Function lcCoordWndToDrw Lib "Litecad.dll" (ByVal hLcWnd As Long, ByVal Xwin As Long, ByVal Ywin As Long, ByVal pXdrw As Long, ByVal pYdrw As Long) As Long
Public Declare Function lcColorIsRGB Lib "Litecad.dll" (ByVal szColor As String) As Long
Public Declare Function lcColorGetRed Lib "Litecad.dll" (ByVal szColor As String) As Long
Public Declare Function lcColorGetGreen Lib "Litecad.dll" (ByVal szColor As String) As Long
Public Declare Function lcColorGetBlue Lib "Litecad.dll" (ByVal szColor As String) As Long
Public Declare Function lcColorGetIndex Lib "Litecad.dll" (ByVal szColor As String) As Long
Public Declare Function lcColorToVal Lib "Litecad.dll" (ByVal szColor As String, ByVal pbRGB As Long, ByVal pIndex As Long, ByVal pR As Long, ByVal pG As Long, ByVal pB As Long) As Long
Public Declare Function lcColorSetPalette Lib "Litecad.dll" (ByVal Index As Long, ByVal R As Long, ByVal G As Long, ByVal B As Long) As Long
Public Declare Function lcColorGetPalette Lib "Litecad.dll" (ByVal Index As Long, ByVal pR As Long, ByVal pG As Long, ByVal pB As Long) As Long
Public Declare Function lcCreateCmdwin Lib "Litecad.dll" (ByVal hWndParent As Long, ByVal Left As Long, ByVal Top As Long, ByVal Width As Long, ByVal Height As Long) As Long
Public Declare Function lcCmdwinResize Lib "Litecad.dll" (ByVal hCmdLine As Long, ByVal Left As Long, ByVal Top As Long, ByVal Width As Long, ByVal Height As Long) As Long
Public Declare Function lcCreatePropwin Lib "Litecad.dll" (ByVal hWndParent As Long, ByVal Left As Long, ByVal Top As Long, ByVal Width As Long, ByVal Height As Long) As Long
Public Declare Function lcPropwinResize Lib "Litecad.dll" (ByVal hPropWnd As Long, ByVal Left As Long, ByVal Top As Long, ByVal Width As Long, ByVal Height As Long) As Long
Public Declare Function lcPropwinUpdate Lib "Litecad.dll" (ByVal hPropWnd As Long, ByVal bSelChanged As Long) As Long
Public Declare Function lcGetErrorCode Lib "Litecad.dll" () As Long
Public Declare Function lcGetErrorStr Lib "Litecad.dll" () As String
Public Declare Function lcExtractPreview Lib "Litecad.dll" (ByVal szFileName As String, ByVal hGlob As Long, ByVal MaxSize As Long) As Long
Public Declare Function lcExtractFileInfo Lib "Litecad.dll" (ByVal szFileName As String, ByVal szGuid As Any, ByVal szComment As Any, ByVal pInt0 As Long, ByVal pInt1 As Long) As Long
Public Declare Function lcGetClientSize Lib "Litecad.dll" (ByVal hWnd As Long, ByVal pWidth As Long, ByVal pHeight As Long) As Long
Public Declare Function lcGetFileName Lib "Litecad.dll" (ByVal hWnd As Long, ByVal Mode As Long) As String
Public Declare Function lcGetValue Lib "Litecad.dll" (ByVal hWnd As Long, ByVal Lef As Long, ByVal Top As Long, ByVal szCaption As String, ByVal szPrompt As String, ByVal szValue As String) As String
Public Declare Sub lcTextOut Lib "Litecad.dll" (ByVal hDC As Long, ByVal x As Long, ByVal y As Long, ByVal szText As String, ByVal ColorRGB As Long)
Public Declare Function lcFilletSetLines Lib "Litecad.dll" (ByVal L1x0 As Double, ByVal L1y0 As Double, ByVal L1x1 As Double, ByVal L1y1 As Double, ByVal L2x0 As Double, ByVal L2y0 As Double, ByVal L2x1 As Double, ByVal L2y1 As Double) As Long
Public Declare Function lcFillet Lib "Litecad.dll" (ByVal Rad As Double, ByVal Bis As Double, ByVal Tang As Double) As Long
Public Declare Function lcFilletGetPoint Lib "Litecad.dll" (ByVal iPnt As Long, ByVal pX As Long, ByVal pY As Long) As Long
Public Declare Function lcCreateCommand Lib "Litecad.dll" (ByVal hLcWnd As Long, ByVal Id As Long, ByVal szName As String, ByVal bNeedSel As Long) As Long
Public Declare Function lcCmdExit Lib "Litecad.dll" () As Long
Public Declare Function lcCmdPrompt Lib "Litecad.dll" (ByVal hCmd As Long, ByVal szText As String) As Long
Public Declare Function lcCmdGetEntByPoint Lib "Litecad.dll" (ByVal hCmd As Long, ByVal Xwnd As Long, ByVal Ywnd As Long) As Long
Public Declare Function lcCmdSelectEnt Lib "Litecad.dll" (ByVal hCmd As Long, ByVal hEntity As Long, ByVal bSelect As Long) As Long
Public Declare Function lcCmdRedraw Lib "Litecad.dll" (ByVal hCmd As Long) As Long
Public Declare Function lcCmdSetFocus Lib "Litecad.dll" (ByVal hCmd As Long) As Long
Public Declare Function lcCmdRegen Lib "Litecad.dll" (ByVal hCmd As Long, ByVal hEnt As Long) As Long
Public Declare Function lcCmdClearPoints Lib "Litecad.dll" (ByVal hCmd As Long) As Long
Public Declare Function lcCmdAddPoint Lib "Litecad.dll" (ByVal hCmd As Long, ByVal Id As Long, ByVal X As Double, ByVal Y As Double) As Long
Public Declare Function lcCmdGetPoint Lib "Litecad.dll" (ByVal hCmd As Long, ByVal Id As Long, ByVal pX As Long, ByVal pY As Long) As Long
Public Declare Function lcCmdSetBasePoint Lib "Litecad.dll" (ByVal hCmd As Long, ByVal bEnable As Long, ByVal X As Double, ByVal Y As Double) As Long
Public Declare Function lcCmdDrawLine Lib "Litecad.dll" (ByVal hCmd As Long, ByVal X0 As Double, ByVal Y0 As Double, ByVal X1 As Double, ByVal Y1 As Double) As Long
Public Declare Function lcCmdDrawPickbox Lib "Litecad.dll" (ByVal hCmd As Long, ByVal Xwnd As Long, ByVal Ywnd As Long) As Long
Public Declare Function lcCmdEqualPoints Lib "Litecad.dll" (ByVal hCmd As Long, ByVal X0 As Double, ByVal Y0 As Double, ByVal X1 As Double, ByVal Y1 As Double, ByVal Delta As Long) As Long
Public Declare Sub lcSurfInitialize Lib "Litecad.dll" (ByVal MaxSectPnt As Long, ByVal AngStep As Double)
Public Declare Sub lcSurfUnInitialize Lib "Litecad.dll" ()
Public Declare Sub lcSurfClearTriangles Lib "Litecad.dll" ()
Public Declare Function lcSurfAddTriangle Lib "Litecad.dll" (ByVal X0 As Double, ByVal Y0 As Double, ByVal Z0 As Double, ByVal X1 As Double, ByVal Y1 As Double, ByVal Z1 As Double, ByVal X2 As Double, ByVal Y2 As Double, ByVal Z2 As Double) As Long
Public Declare Function lcSurfGetZ Lib "Litecad.dll" (ByVal X As Double, ByVal Y As Double, ByVal pZ As Long) As Long
Public Declare Function lcSurfGetZ_dbg Lib "Litecad.dll" (ByVal X As Double, ByVal Y As Double, ByVal pZ As Long, ByVal pX0 As Long, ByVal pY0 As Long, ByVal pZ0 As Long, ByVal pX1 As Long, ByVal pY1 As Long, ByVal pZ1 As Long, ByVal pX2 As Long, ByVal pY2 As Long, ByVal pZ2 As Long) As Long
Public Declare Sub lcSurfClearPlan Lib "Litecad.dll" ()
Public Declare Function lcSurfAddPlanVer Lib "Litecad.dll" (ByVal X As Double, ByVal Y As Double, ByVal Bulge As Double) As Long
Public Declare Function lcSurfMakeSection Lib "Litecad.dll" () As Long
Public Declare Function lcSurfGetSectPoint Lib "Litecad.dll" (ByVal iPnt As Long, ByVal pX As Long, ByVal pY As Long, ByVal pZ As Long) As Long
Public Declare Sub lcCrossSetTolerance Lib "Litecad.dll" (ByVal Zero1 As Double, ByVal One1 As Double, ByVal Zero2 As Double, ByVal One2 As Double, ByVal NearPt As Double, ByVal Clas As Double, ByVal CutGr As Double, ByVal RigPt As Double)
Public Declare Function lcCrossClear Lib "Litecad.dll" () As Long
Public Declare Function lcCrossBegin Lib "Litecad.dll" (ByVal PlineType As Long) As Long
Public Declare Function lcCrossAddPoint Lib "Litecad.dll" (ByVal X As Double, ByVal Y As Double) As Long
Public Declare Function lcCrossEnd Lib "Litecad.dll" () As Long
Public Declare Function lcCrossCalcArea Lib "Litecad.dll" () As Long
Public Declare Function lcCrossCalcArea2 Lib "Litecad.dll" (ByVal hDrw As Long, ByVal GroundKey As Long, ByVal RoadKey As Long, ByVal LinkKey As Long) As Long
Public Declare Function lcCrossGetArea Lib "Litecad.dll" (ByVal iArea As Long, ByVal pAreaVal As Long, ByVal pNumPnts As Long) As Long
Public Declare Function lcCrossGetAreaPoint Lib "Litecad.dll" (ByVal iArea As Long, ByVal iPnt As Long, ByVal pX As Long, ByVal pY As Long) As Long
Public Declare Sub lcEventReturnCode Lib "Litecad.dll" (ByVal code As Long)
Public Declare Sub lcEventsEnable Lib "Litecad.dll" (ByVal bEnable As Long)
Public Declare Sub lcOnEventMouseMove Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventMouseDown Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventMouseUp Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventMouseDblClk Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventMouseSnap Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventMouseLeave Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventMouseWheel Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventKeyDown Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventPaint Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventZoom Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventSelectView Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventGetPoint Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventAddCommand Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventCmdStart Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventCmdFinish Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventCmdMouseDown Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventCmdMouseUp Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventCmdMouseMove Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventCmdString Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventAddEntity Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventRegen Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventFioProgress Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventSelection Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventPropChanged Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventGripSelect Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventGripMove Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventEntErase Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventEntMove Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventEntRotate Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventEntScale Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventEntMirror Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventEntProp Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventHelp Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventAddStr Lib "Litecad.dll" (ByVal pFunc As Any)
Public Declare Sub lcOnEventFontReplace Lib "Litecad.dll" (ByVal pFunc As Any)
